// Code generated by hertz generator.

package social

import (
	"Tiktok/biz/model/common"
	"Tiktok/biz/model/user"
	"context"

	social "Tiktok/biz/model/social"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

type SocialSever interface {
	RelationAction(toUserId string, actionType string, userId string) (int, string)
	FollowingList(userId string, pageNum int64, pageSize int64) (int, string, []*user.UserInfo, bool)
	FollowerList(userId string, pageNum int64, pageSize int64) (int, string, []*user.UserInfo, bool)
	FriendList(userId string, pageNum int64, pageSize int64) (int, string, []*user.UserInfo, bool)
}
type SocialHandler struct {
	socialService SocialSever
}

func NewSocialHandler(service SocialSever) *SocialHandler {
	return &SocialHandler{socialService: service}
}

var (
	RelationAction func(ctx context.Context, c *app.RequestContext)
	FollowingList  func(ctx context.Context, c *app.RequestContext)
	FollowerList   func(ctx context.Context, c *app.RequestContext)
	FriendList     func(ctx context.Context, c *app.RequestContext)
)

// RelationAction .
// @router /relation/action [POST]
func (h *SocialHandler) RelationAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.RelationActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	userId := ctx.Value("user_id").(string)
	code, msg := h.socialService.RelationAction(req.ToUserId, req.ActionType, userId)
	resp := new(social.RelationActionResp)
	resp.Base.Code = int32(code)
	resp.Base.Msg = msg
	c.JSON(consts.StatusOK, resp)
}

// FollowingList .
// @router /following/list [GET]
func (h *SocialHandler) FollowingList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.FollowingListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	code, msg, userInfos, _ := h.socialService.FollowingList(req.UserId, req.PageNum, req.PageSize)
	resp := &social.FollowingListResp{
		Base: &common.Base{Code: int32(code), Msg: msg},
		Data: &social.SocialData{Items: userInfos, Total: int64(len(userInfos))},
	}
	c.JSON(consts.StatusOK, resp)
}

// FollowerList .
// @router /follower/list [GET]
func (h *SocialHandler) FollowerList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.FollowerListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	code, msg, userInfos, _ := h.socialService.FollowerList(req.UserId, req.PageNum, req.PageSize)
	resp := &social.FollowingListResp{
		Base: &common.Base{Code: int32(code), Msg: msg},
		Data: &social.SocialData{Items: userInfos, Total: int64(len(userInfos))},
	}
	c.JSON(consts.StatusOK, resp)
}

// FriendList .
// @router /friend/list [GET]
func (h *SocialHandler) FriendList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.FriendListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	userId := ctx.Value("user_id").(string)
	code, msg, userInfos, _ := h.socialService.FriendList(userId, req.PageNum, req.PageSize)
	resp := &social.FollowingListResp{
		Base: &common.Base{Code: int32(code), Msg: msg},
		Data: &social.SocialData{Items: userInfos, Total: int64(len(userInfos))},
	}
	c.JSON(consts.StatusOK, resp)
}
