// Code generated by hertz generator.

package social

import (
	"Tiktok/biz/model/common"
	"Tiktok/biz/model/user"
	"context"
	"log"

	"Tiktok/biz/model/social"

	"Tiktok/pkg/consts"

	"github.com/cloudwego/hertz/pkg/app"
)

type SocialSever interface {
	RelationAction(toUserId string, actionType string, userId string) (int32, error)
	FollowingList(userId string, pageNum int64, pageSize int64) (int32, error, []*user.UserInfo)
	FollowerList(userId string, pageNum int64, pageSize int64) (int32, error, []*user.UserInfo)
	FriendList(userId string, pageNum int64, pageSize int64) (int32, error, []*user.UserInfo)
}
type SocialHandler struct {
	socialService SocialSever
}

func NewSocialHandler(service SocialSever) *SocialHandler {
	return &SocialHandler{socialService: service}
}

var (
	RelationAction func(ctx context.Context, c *app.RequestContext)
	FollowingList  func(ctx context.Context, c *app.RequestContext)
	FollowerList   func(ctx context.Context, c *app.RequestContext)
	FriendList     func(ctx context.Context, c *app.RequestContext)
)

// RelationAction .
// @router /relation/action [POST]
func (h *SocialHandler) RelationAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.RelationActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := &social.RelationActionResp{
			Base: &common.Base{Code: consts.SocialReqValidError, Msg: consts.GetErrorCodeMsg(consts.SocialReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	userId := ctx.Value("user_id").(string)
	code, err := h.socialService.RelationAction(req.ToUserId, req.ActionType, userId)
	if err != nil {
		log.Println("relation action err", err)
	}
	resp := new(social.RelationActionResp)
	resp.Base = &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)}
	c.JSON(200, resp)
}

// FollowingList .
// @router /following/list [GET]
func (h *SocialHandler) FollowingList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.FollowingListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := &social.RelationActionResp{
			Base: &common.Base{Code: consts.SocialReqValidError, Msg: consts.GetErrorCodeMsg(consts.SocialReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	code, err, userInfos := h.socialService.FollowingList(req.UserId, req.PageNum, req.PageSize)
	resp := &social.FollowingListResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data: &social.SocialData{Items: userInfos, Total: int64(len(userInfos))},
	}
	c.JSON(200, resp)
}

// FollowerList .
// @router /follower/list [GET]
func (h *SocialHandler) FollowerList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.FollowerListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := &social.RelationActionResp{
			Base: &common.Base{Code: consts.SocialReqValidError, Msg: consts.GetErrorCodeMsg(consts.SocialReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	code, err, userInfos := h.socialService.FollowerList(req.UserId, req.PageNum, req.PageSize)
	if err != nil {
		log.Println("follower list err", err)
	}
	resp := &social.FollowingListResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data: &social.SocialData{Items: userInfos, Total: int64(len(userInfos))},
	}
	c.JSON(200, resp)
}

// FriendList .
// @router /friend/list [GET]
func (h *SocialHandler) FriendList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.FriendListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := &social.RelationActionResp{
			Base: &common.Base{Code: consts.SocialReqValidError, Msg: consts.GetErrorCodeMsg(consts.SocialReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	userId := ctx.Value("user_id").(string)
	code, err, userInfos := h.socialService.FriendList(userId, req.PageNum, req.PageSize)
	if err != nil {
		log.Println("friend list err", err)
	}
	resp := &social.FollowingListResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data: &social.SocialData{Items: userInfos, Total: int64(len(userInfos))},
	}
	c.JSON(200, resp)
}
