// Code generated by Kitex v0.16.1. DO NOT EDIT.

package videoservice

import (
	video "Tiktok/kitex_gen/video"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"VideoPublish": kitex.NewMethodInfo(
		videoPublishHandler,
		newVideoPublishArgs,
		newVideoPublishResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"VideoList": kitex.NewMethodInfo(
		videoListHandler,
		newVideoListArgs,
		newVideoListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"VideoSearch": kitex.NewMethodInfo(
		videoSearchHandler,
		newVideoSearchArgs,
		newVideoSearchResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"VideoPopular": kitex.NewMethodInfo(
		videoPopularHandler,
		newVideoPopularArgs,
		newVideoPopularResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"VideoStream": kitex.NewMethodInfo(
		videoStreamHandler,
		newVideoStreamArgs,
		newVideoStreamResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"BatchGetVideo": kitex.NewMethodInfo(
		batchGetVideoHandler,
		newBatchGetVideoArgs,
		newBatchGetVideoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	videoServiceServiceInfo                = NewServiceInfo()
	videoServiceServiceInfoForClient       = NewServiceInfoForClient()
	videoServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return videoServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return videoServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return videoServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "VideoService"
	handlerType := (*video.VideoService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "video",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func videoPublishHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(video.VideoPublishReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(video.VideoService).VideoPublish(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *VideoPublishArgs:
		success, err := handler.(video.VideoService).VideoPublish(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*VideoPublishResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newVideoPublishArgs() interface{} {
	return &VideoPublishArgs{}
}

func newVideoPublishResult() interface{} {
	return &VideoPublishResult{}
}

type VideoPublishArgs struct {
	Req *video.VideoPublishReq
}

func (p *VideoPublishArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *VideoPublishArgs) Unmarshal(in []byte) error {
	msg := new(video.VideoPublishReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var VideoPublishArgs_Req_DEFAULT *video.VideoPublishReq

func (p *VideoPublishArgs) GetReq() *video.VideoPublishReq {
	if !p.IsSetReq() {
		return VideoPublishArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *VideoPublishArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoPublishArgs) GetFirstArgument() interface{} {
	return p.Req
}

type VideoPublishResult struct {
	Success *video.VideoPublishResp
}

var VideoPublishResult_Success_DEFAULT *video.VideoPublishResp

func (p *VideoPublishResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *VideoPublishResult) Unmarshal(in []byte) error {
	msg := new(video.VideoPublishResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *VideoPublishResult) GetSuccess() *video.VideoPublishResp {
	if !p.IsSetSuccess() {
		return VideoPublishResult_Success_DEFAULT
	}
	return p.Success
}

func (p *VideoPublishResult) SetSuccess(x interface{}) {
	p.Success = x.(*video.VideoPublishResp)
}

func (p *VideoPublishResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoPublishResult) GetResult() interface{} {
	return p.Success
}

func videoListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(video.VideoListReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(video.VideoService).VideoList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *VideoListArgs:
		success, err := handler.(video.VideoService).VideoList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*VideoListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newVideoListArgs() interface{} {
	return &VideoListArgs{}
}

func newVideoListResult() interface{} {
	return &VideoListResult{}
}

type VideoListArgs struct {
	Req *video.VideoListReq
}

func (p *VideoListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *VideoListArgs) Unmarshal(in []byte) error {
	msg := new(video.VideoListReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var VideoListArgs_Req_DEFAULT *video.VideoListReq

func (p *VideoListArgs) GetReq() *video.VideoListReq {
	if !p.IsSetReq() {
		return VideoListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *VideoListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type VideoListResult struct {
	Success *video.VideoListResp
}

var VideoListResult_Success_DEFAULT *video.VideoListResp

func (p *VideoListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *VideoListResult) Unmarshal(in []byte) error {
	msg := new(video.VideoListResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *VideoListResult) GetSuccess() *video.VideoListResp {
	if !p.IsSetSuccess() {
		return VideoListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *VideoListResult) SetSuccess(x interface{}) {
	p.Success = x.(*video.VideoListResp)
}

func (p *VideoListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoListResult) GetResult() interface{} {
	return p.Success
}

func videoSearchHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(video.VideoSearchReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(video.VideoService).VideoSearch(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *VideoSearchArgs:
		success, err := handler.(video.VideoService).VideoSearch(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*VideoSearchResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newVideoSearchArgs() interface{} {
	return &VideoSearchArgs{}
}

func newVideoSearchResult() interface{} {
	return &VideoSearchResult{}
}

type VideoSearchArgs struct {
	Req *video.VideoSearchReq
}

func (p *VideoSearchArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *VideoSearchArgs) Unmarshal(in []byte) error {
	msg := new(video.VideoSearchReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var VideoSearchArgs_Req_DEFAULT *video.VideoSearchReq

func (p *VideoSearchArgs) GetReq() *video.VideoSearchReq {
	if !p.IsSetReq() {
		return VideoSearchArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *VideoSearchArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoSearchArgs) GetFirstArgument() interface{} {
	return p.Req
}

type VideoSearchResult struct {
	Success *video.VideoSearchResp
}

var VideoSearchResult_Success_DEFAULT *video.VideoSearchResp

func (p *VideoSearchResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *VideoSearchResult) Unmarshal(in []byte) error {
	msg := new(video.VideoSearchResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *VideoSearchResult) GetSuccess() *video.VideoSearchResp {
	if !p.IsSetSuccess() {
		return VideoSearchResult_Success_DEFAULT
	}
	return p.Success
}

func (p *VideoSearchResult) SetSuccess(x interface{}) {
	p.Success = x.(*video.VideoSearchResp)
}

func (p *VideoSearchResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoSearchResult) GetResult() interface{} {
	return p.Success
}

func videoPopularHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(video.VideoHotReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(video.VideoService).VideoPopular(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *VideoPopularArgs:
		success, err := handler.(video.VideoService).VideoPopular(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*VideoPopularResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newVideoPopularArgs() interface{} {
	return &VideoPopularArgs{}
}

func newVideoPopularResult() interface{} {
	return &VideoPopularResult{}
}

type VideoPopularArgs struct {
	Req *video.VideoHotReq
}

func (p *VideoPopularArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *VideoPopularArgs) Unmarshal(in []byte) error {
	msg := new(video.VideoHotReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var VideoPopularArgs_Req_DEFAULT *video.VideoHotReq

func (p *VideoPopularArgs) GetReq() *video.VideoHotReq {
	if !p.IsSetReq() {
		return VideoPopularArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *VideoPopularArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoPopularArgs) GetFirstArgument() interface{} {
	return p.Req
}

type VideoPopularResult struct {
	Success *video.VideoHotResp
}

var VideoPopularResult_Success_DEFAULT *video.VideoHotResp

func (p *VideoPopularResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *VideoPopularResult) Unmarshal(in []byte) error {
	msg := new(video.VideoHotResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *VideoPopularResult) GetSuccess() *video.VideoHotResp {
	if !p.IsSetSuccess() {
		return VideoPopularResult_Success_DEFAULT
	}
	return p.Success
}

func (p *VideoPopularResult) SetSuccess(x interface{}) {
	p.Success = x.(*video.VideoHotResp)
}

func (p *VideoPopularResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoPopularResult) GetResult() interface{} {
	return p.Success
}

func videoStreamHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(video.VideoStreamReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(video.VideoService).VideoStream(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *VideoStreamArgs:
		success, err := handler.(video.VideoService).VideoStream(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*VideoStreamResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newVideoStreamArgs() interface{} {
	return &VideoStreamArgs{}
}

func newVideoStreamResult() interface{} {
	return &VideoStreamResult{}
}

type VideoStreamArgs struct {
	Req *video.VideoStreamReq
}

func (p *VideoStreamArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *VideoStreamArgs) Unmarshal(in []byte) error {
	msg := new(video.VideoStreamReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var VideoStreamArgs_Req_DEFAULT *video.VideoStreamReq

func (p *VideoStreamArgs) GetReq() *video.VideoStreamReq {
	if !p.IsSetReq() {
		return VideoStreamArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *VideoStreamArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoStreamArgs) GetFirstArgument() interface{} {
	return p.Req
}

type VideoStreamResult struct {
	Success *video.VideoStreamResp
}

var VideoStreamResult_Success_DEFAULT *video.VideoStreamResp

func (p *VideoStreamResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *VideoStreamResult) Unmarshal(in []byte) error {
	msg := new(video.VideoStreamResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *VideoStreamResult) GetSuccess() *video.VideoStreamResp {
	if !p.IsSetSuccess() {
		return VideoStreamResult_Success_DEFAULT
	}
	return p.Success
}

func (p *VideoStreamResult) SetSuccess(x interface{}) {
	p.Success = x.(*video.VideoStreamResp)
}

func (p *VideoStreamResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoStreamResult) GetResult() interface{} {
	return p.Success
}

func batchGetVideoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(video.BatchGetVideoReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(video.VideoService).BatchGetVideo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BatchGetVideoArgs:
		success, err := handler.(video.VideoService).BatchGetVideo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BatchGetVideoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBatchGetVideoArgs() interface{} {
	return &BatchGetVideoArgs{}
}

func newBatchGetVideoResult() interface{} {
	return &BatchGetVideoResult{}
}

type BatchGetVideoArgs struct {
	Req *video.BatchGetVideoReq
}

func (p *BatchGetVideoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BatchGetVideoArgs) Unmarshal(in []byte) error {
	msg := new(video.BatchGetVideoReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BatchGetVideoArgs_Req_DEFAULT *video.BatchGetVideoReq

func (p *BatchGetVideoArgs) GetReq() *video.BatchGetVideoReq {
	if !p.IsSetReq() {
		return BatchGetVideoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BatchGetVideoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BatchGetVideoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BatchGetVideoResult struct {
	Success *video.BatchGetVideoResp
}

var BatchGetVideoResult_Success_DEFAULT *video.BatchGetVideoResp

func (p *BatchGetVideoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BatchGetVideoResult) Unmarshal(in []byte) error {
	msg := new(video.BatchGetVideoResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BatchGetVideoResult) GetSuccess() *video.BatchGetVideoResp {
	if !p.IsSetSuccess() {
		return BatchGetVideoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BatchGetVideoResult) SetSuccess(x interface{}) {
	p.Success = x.(*video.BatchGetVideoResp)
}

func (p *BatchGetVideoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BatchGetVideoResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) VideoPublish(ctx context.Context, Req *video.VideoPublishReq) (r *video.VideoPublishResp, err error) {
	var _args VideoPublishArgs
	_args.Req = Req
	var _result VideoPublishResult
	if err = p.c.Call(ctx, "VideoPublish", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VideoList(ctx context.Context, Req *video.VideoListReq) (r *video.VideoListResp, err error) {
	var _args VideoListArgs
	_args.Req = Req
	var _result VideoListResult
	if err = p.c.Call(ctx, "VideoList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VideoSearch(ctx context.Context, Req *video.VideoSearchReq) (r *video.VideoSearchResp, err error) {
	var _args VideoSearchArgs
	_args.Req = Req
	var _result VideoSearchResult
	if err = p.c.Call(ctx, "VideoSearch", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VideoPopular(ctx context.Context, Req *video.VideoHotReq) (r *video.VideoHotResp, err error) {
	var _args VideoPopularArgs
	_args.Req = Req
	var _result VideoPopularResult
	if err = p.c.Call(ctx, "VideoPopular", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VideoStream(ctx context.Context, Req *video.VideoStreamReq) (r *video.VideoStreamResp, err error) {
	var _args VideoStreamArgs
	_args.Req = Req
	var _result VideoStreamResult
	if err = p.c.Call(ctx, "VideoStream", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchGetVideo(ctx context.Context, Req *video.BatchGetVideoReq) (r *video.BatchGetVideoResp, err error) {
	var _args BatchGetVideoArgs
	_args.Req = Req
	var _result BatchGetVideoResult
	if err = p.c.Call(ctx, "BatchGetVideo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
