// Code generated by hertz generator.

package main

import (
	"Tiktok/biz/dao/db"
	"Tiktok/biz/dao/redis"
	"Tiktok/biz/handler"

	"Tiktok/biz/router"
	"Tiktok/biz/service"
	"Tiktok/pkg/conf"

	"log"
)

func main() {
	cfg, err := conf.Load([]string{"./pkg/conf"})
	if err != nil {
		log.Fatal("加载config.yaml错误", err)
	}
	log.Println(cfg)

	rdb := redis.InitRedis()
	defer rdb.Close()

	ddb := db.InitDb()
	mysqlDb := db.NewMySQLdb(ddb)

	svc := service.NewService(mysqlDb)
	h := handler.NewHandler(svc)

	userSVC := service.NewUserService(mysqlDb, mysqlDb)
	uh := handler.NewUserHandler(userSVC)

	defer ddb.Close()

	router.SetRouters(h, uh)
}
