// Code generated by hertz generator.

package main

import (
	"Tiktok/biz/cache"
	"Tiktok/biz/dao"
	"Tiktok/biz/handler"

	"Tiktok/biz/router"
	"Tiktok/biz/service"
	"Tiktok/pkg/config"

	"log"
)

func main() {

	cfg, err := config.Load([]string{"./pkg/config"})
	if err != nil {
		log.Fatal("加载config.yaml错误", err)
	}
	log.Println(cfg)

	rdb := cache.InitRedis()
	re := cache.NewRedis(rdb)
	defer rdb.Close()

	ddb := dao.InitDb()
	mysqlDb := dao.NewMySQLdb(ddb)

	likeSVC := service.NewLikeVideoService(mysqlDb, mysqlDb)
	likesHandler := handler.NewLikesHandler(likeSVC, likeSVC)

	commentSVC := service.NewCommentService(mysqlDb)
	commentHandler := handler.NewCommentHandler(commentSVC)

	userSVC := service.NewUserService(mysqlDb, mysqlDb, re)
	userHandler := handler.NewUserHandler(userSVC)

	videoSVC := service.NewVideoService(mysqlDb, re)
	videoHandler := handler.NewVideoHandler(videoSVC)

	socialSVC := service.NewSocialService(mysqlDb, mysqlDb)
	socialHandler := handler.NewSocialHandler(socialSVC)

	WebsocketHandler := handler.NewWebsocketSever(mysqlDb, re)

	defer ddb.Close()
	go service.Manager.Start(mysqlDb, re)

	router.SetRouters(commentHandler, userHandler, videoHandler, socialHandler, likesHandler, WebsocketHandler)

}
