// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: mfa.proto

package mfa

import (
	_ "Tiktok/biz/model/api"
	common "Tiktok/biz/model/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MfaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret string `protobuf:"bytes,1,opt,name=Secret,proto3" form:"Secret" json:"secret" query:"Secret"`
	Qrcode string `protobuf:"bytes,2,opt,name=Qrcode,proto3" form:"Qrcode" json:"qrcode" query:"Qrcode"`
}

func (x *MfaData) Reset() {
	*x = MfaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mfa_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MfaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaData) ProtoMessage() {}

func (x *MfaData) ProtoReflect() protoreflect.Message {
	mi := &file_mfa_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaData.ProtoReflect.Descriptor instead.
func (*MfaData) Descriptor() ([]byte, []int) {
	return file_mfa_proto_rawDescGZIP(), []int{0}
}

func (x *MfaData) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *MfaData) GetQrcode() string {
	if x != nil {
		return x.Qrcode
	}
	return ""
}

type MfaQrcodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MfaQrcodeReq) Reset() {
	*x = MfaQrcodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mfa_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MfaQrcodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaQrcodeReq) ProtoMessage() {}

func (x *MfaQrcodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_mfa_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaQrcodeReq.ProtoReflect.Descriptor instead.
func (*MfaQrcodeReq) Descriptor() ([]byte, []int) {
	return file_mfa_proto_rawDescGZIP(), []int{1}
}

type MfaQrcodeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *common.Base `protobuf:"bytes,1,opt,name=Base,proto3" form:"Base" json:"base" query:"Base"`
	Data *MfaData     `protobuf:"bytes,2,opt,name=Data,proto3" form:"Data" json:"data" query:"Data"`
}

func (x *MfaQrcodeResp) Reset() {
	*x = MfaQrcodeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mfa_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MfaQrcodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaQrcodeResp) ProtoMessage() {}

func (x *MfaQrcodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_mfa_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaQrcodeResp.ProtoReflect.Descriptor instead.
func (*MfaQrcodeResp) Descriptor() ([]byte, []int) {
	return file_mfa_proto_rawDescGZIP(), []int{2}
}

func (x *MfaQrcodeResp) GetBase() *common.Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *MfaQrcodeResp) GetData() *MfaData {
	if x != nil {
		return x.Data
	}
	return nil
}

type MfaBindReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   string `protobuf:"bytes,1,opt,name=Code,proto3" form:"code" json:"code,omitempty"`
	Secret string `protobuf:"bytes,2,opt,name=Secret,proto3" form:"secret" json:"secret,omitempty"`
}

func (x *MfaBindReq) Reset() {
	*x = MfaBindReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mfa_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MfaBindReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaBindReq) ProtoMessage() {}

func (x *MfaBindReq) ProtoReflect() protoreflect.Message {
	mi := &file_mfa_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaBindReq.ProtoReflect.Descriptor instead.
func (*MfaBindReq) Descriptor() ([]byte, []int) {
	return file_mfa_proto_rawDescGZIP(), []int{3}
}

func (x *MfaBindReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MfaBindReq) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type MfaBindResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *common.Base `protobuf:"bytes,1,opt,name=Base,proto3" form:"Base" json:"base" query:"Base"`
}

func (x *MfaBindResp) Reset() {
	*x = MfaBindResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mfa_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MfaBindResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaBindResp) ProtoMessage() {}

func (x *MfaBindResp) ProtoReflect() protoreflect.Message {
	mi := &file_mfa_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaBindResp.ProtoReflect.Descriptor instead.
func (*MfaBindResp) Descriptor() ([]byte, []int) {
	return file_mfa_proto_rawDescGZIP(), []int{4}
}

func (x *MfaBindResp) GetBase() *common.Base {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_mfa_proto protoreflect.FileDescriptor

var file_mfa_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x66, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x66, 0x61,
	0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x07, 0x4d, 0x66, 0x61,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x29, 0x0a, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x11, 0xca, 0xf3, 0x18, 0x0d, 0x6a, 0x73, 0x6f, 0x6e, 0x3a, 0x22,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0x52, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12,
	0x29, 0x0a, 0x06, 0x51, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x11, 0xca, 0xf3, 0x18, 0x0d, 0x6a, 0x73, 0x6f, 0x6e, 0x3a, 0x22, 0x71, 0x72, 0x63, 0x6f, 0x64,
	0x65, 0x22, 0x52, 0x06, 0x51, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x4d, 0x66,
	0x61, 0x51, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x22, 0x75, 0x0a, 0x0d, 0x4d, 0x66,
	0x61, 0x51, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x04, 0x42,
	0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x42, 0x0f, 0xca, 0xf3, 0x18, 0x0b, 0x6a, 0x73, 0x6f,
	0x6e, 0x3a, 0x22, 0x62, 0x61, 0x73, 0x65, 0x22, 0x52, 0x04, 0x42, 0x61, 0x73, 0x65, 0x12, 0x31,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d,
	0x66, 0x61, 0x2e, 0x4d, 0x66, 0x61, 0x44, 0x61, 0x74, 0x61, 0x42, 0x0f, 0xca, 0xf3, 0x18, 0x0b,
	0x6a, 0x73, 0x6f, 0x6e, 0x3a, 0x22, 0x64, 0x61, 0x74, 0x61, 0x22, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x4e, 0x0a, 0x0a, 0x4d, 0x66, 0x61, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x1c, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x08, 0xca,
	0xbb, 0x18, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a,
	0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xca,
	0xbb, 0x18, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x22, 0x40, 0x0a, 0x0b, 0x4d, 0x66, 0x61, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x31, 0x0a, 0x04, 0x42, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x42, 0x0f, 0xca, 0xf3,
	0x18, 0x0b, 0x6a, 0x73, 0x6f, 0x6e, 0x3a, 0x22, 0x62, 0x61, 0x73, 0x65, 0x22, 0x52, 0x04, 0x42,
	0x61, 0x73, 0x65, 0x42, 0x16, 0x5a, 0x14, 0x54, 0x69, 0x6b, 0x74, 0x6f, 0x6b, 0x2f, 0x62, 0x69,
	0x7a, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x6d, 0x66, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_mfa_proto_rawDescOnce sync.Once
	file_mfa_proto_rawDescData = file_mfa_proto_rawDesc
)

func file_mfa_proto_rawDescGZIP() []byte {
	file_mfa_proto_rawDescOnce.Do(func() {
		file_mfa_proto_rawDescData = protoimpl.X.CompressGZIP(file_mfa_proto_rawDescData)
	})
	return file_mfa_proto_rawDescData
}

var file_mfa_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mfa_proto_goTypes = []interface{}{
	(*MfaData)(nil),       // 0: mfa.MfaData
	(*MfaQrcodeReq)(nil),  // 1: mfa.MfaQrcodeReq
	(*MfaQrcodeResp)(nil), // 2: mfa.MfaQrcodeResp
	(*MfaBindReq)(nil),    // 3: mfa.MfaBindReq
	(*MfaBindResp)(nil),   // 4: mfa.MfaBindResp
	(*common.Base)(nil),   // 5: common.Base
}
var file_mfa_proto_depIdxs = []int32{
	5, // 0: mfa.MfaQrcodeResp.Base:type_name -> common.Base
	0, // 1: mfa.MfaQrcodeResp.Data:type_name -> mfa.MfaData
	5, // 2: mfa.MfaBindResp.Base:type_name -> common.Base
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mfa_proto_init() }
func file_mfa_proto_init() {
	if File_mfa_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mfa_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MfaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mfa_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MfaQrcodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mfa_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MfaQrcodeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mfa_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MfaBindReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mfa_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MfaBindResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mfa_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mfa_proto_goTypes,
		DependencyIndexes: file_mfa_proto_depIdxs,
		MessageInfos:      file_mfa_proto_msgTypes,
	}.Build()
	File_mfa_proto = out.File
	file_mfa_proto_rawDesc = nil
	file_mfa_proto_goTypes = nil
	file_mfa_proto_depIdxs = nil
}
