// Code generated by Kitex v0.16.1. DO NOT EDIT.

package likeservice

import (
	react "Tiktok/kitex_gen/react"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"LikeAction": kitex.NewMethodInfo(
		likeActionHandler,
		newLikeActionArgs,
		newLikeActionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"LikeList": kitex.NewMethodInfo(
		likeListHandler,
		newLikeListArgs,
		newLikeListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	likeServiceServiceInfo                = NewServiceInfo()
	likeServiceServiceInfoForClient       = NewServiceInfoForClient()
	likeServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return likeServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return likeServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return likeServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "LikeService"
	handlerType := (*react.LikeService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "react",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func likeActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(react.LikeActionReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(react.LikeService).LikeAction(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *LikeActionArgs:
		success, err := handler.(react.LikeService).LikeAction(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LikeActionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newLikeActionArgs() interface{} {
	return &LikeActionArgs{}
}

func newLikeActionResult() interface{} {
	return &LikeActionResult{}
}

type LikeActionArgs struct {
	Req *react.LikeActionReq
}

func (p *LikeActionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *LikeActionArgs) Unmarshal(in []byte) error {
	msg := new(react.LikeActionReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LikeActionArgs_Req_DEFAULT *react.LikeActionReq

func (p *LikeActionArgs) GetReq() *react.LikeActionReq {
	if !p.IsSetReq() {
		return LikeActionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LikeActionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LikeActionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type LikeActionResult struct {
	Success *react.LikeActionResp
}

var LikeActionResult_Success_DEFAULT *react.LikeActionResp

func (p *LikeActionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *LikeActionResult) Unmarshal(in []byte) error {
	msg := new(react.LikeActionResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LikeActionResult) GetSuccess() *react.LikeActionResp {
	if !p.IsSetSuccess() {
		return LikeActionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LikeActionResult) SetSuccess(x interface{}) {
	p.Success = x.(*react.LikeActionResp)
}

func (p *LikeActionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LikeActionResult) GetResult() interface{} {
	return p.Success
}

func likeListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(react.LikeListReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(react.LikeService).LikeList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *LikeListArgs:
		success, err := handler.(react.LikeService).LikeList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LikeListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newLikeListArgs() interface{} {
	return &LikeListArgs{}
}

func newLikeListResult() interface{} {
	return &LikeListResult{}
}

type LikeListArgs struct {
	Req *react.LikeListReq
}

func (p *LikeListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *LikeListArgs) Unmarshal(in []byte) error {
	msg := new(react.LikeListReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LikeListArgs_Req_DEFAULT *react.LikeListReq

func (p *LikeListArgs) GetReq() *react.LikeListReq {
	if !p.IsSetReq() {
		return LikeListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LikeListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LikeListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type LikeListResult struct {
	Success *react.LikeListResp
}

var LikeListResult_Success_DEFAULT *react.LikeListResp

func (p *LikeListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *LikeListResult) Unmarshal(in []byte) error {
	msg := new(react.LikeListResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LikeListResult) GetSuccess() *react.LikeListResp {
	if !p.IsSetSuccess() {
		return LikeListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LikeListResult) SetSuccess(x interface{}) {
	p.Success = x.(*react.LikeListResp)
}

func (p *LikeListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LikeListResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) LikeAction(ctx context.Context, Req *react.LikeActionReq) (r *react.LikeActionResp, err error) {
	var _args LikeActionArgs
	_args.Req = Req
	var _result LikeActionResult
	if err = p.c.Call(ctx, "LikeAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LikeList(ctx context.Context, Req *react.LikeListReq) (r *react.LikeListResp, err error) {
	var _args LikeListArgs
	_args.Req = Req
	var _result LikeListResult
	if err = p.c.Call(ctx, "LikeList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
