// Code generated by Kitex v0.16.1. DO NOT EDIT.

package commentservice

import (
	react "Tiktok/kitex_gen/react"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CommentPublish(ctx context.Context, Req *react.CommentPublishReq, callOptions ...callopt.Option) (r *react.CommentPublishResp, err error)
	CommentList(ctx context.Context, Req *react.CommentListReq, callOptions ...callopt.Option) (r *react.CommentListResp, err error)
	CommentDelete(ctx context.Context, Req *react.CommentDeleteReq, callOptions ...callopt.Option) (r *react.CommentDeleteResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCommentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCommentServiceClient struct {
	*kClient
}

func (p *kCommentServiceClient) CommentPublish(ctx context.Context, Req *react.CommentPublishReq, callOptions ...callopt.Option) (r *react.CommentPublishResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentPublish(ctx, Req)
}

func (p *kCommentServiceClient) CommentList(ctx context.Context, Req *react.CommentListReq, callOptions ...callopt.Option) (r *react.CommentListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentList(ctx, Req)
}

func (p *kCommentServiceClient) CommentDelete(ctx context.Context, Req *react.CommentDeleteReq, callOptions ...callopt.Option) (r *react.CommentDeleteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentDelete(ctx, Req)
}
