// Code generated by Kitex v0.16.1. DO NOT EDIT.

package commentservice

import (
	react "Tiktok/kitex_gen/react"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CommentPublish": kitex.NewMethodInfo(
		commentPublishHandler,
		newCommentPublishArgs,
		newCommentPublishResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CommentList": kitex.NewMethodInfo(
		commentListHandler,
		newCommentListArgs,
		newCommentListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CommentDelete": kitex.NewMethodInfo(
		commentDeleteHandler,
		newCommentDeleteArgs,
		newCommentDeleteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	commentServiceServiceInfo                = NewServiceInfo()
	commentServiceServiceInfoForClient       = NewServiceInfoForClient()
	commentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return commentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return commentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return commentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CommentService"
	handlerType := (*react.CommentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "react",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func commentPublishHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(react.CommentPublishReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(react.CommentService).CommentPublish(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CommentPublishArgs:
		success, err := handler.(react.CommentService).CommentPublish(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CommentPublishResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCommentPublishArgs() interface{} {
	return &CommentPublishArgs{}
}

func newCommentPublishResult() interface{} {
	return &CommentPublishResult{}
}

type CommentPublishArgs struct {
	Req *react.CommentPublishReq
}

func (p *CommentPublishArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CommentPublishArgs) Unmarshal(in []byte) error {
	msg := new(react.CommentPublishReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CommentPublishArgs_Req_DEFAULT *react.CommentPublishReq

func (p *CommentPublishArgs) GetReq() *react.CommentPublishReq {
	if !p.IsSetReq() {
		return CommentPublishArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CommentPublishArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CommentPublishArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CommentPublishResult struct {
	Success *react.CommentPublishResp
}

var CommentPublishResult_Success_DEFAULT *react.CommentPublishResp

func (p *CommentPublishResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CommentPublishResult) Unmarshal(in []byte) error {
	msg := new(react.CommentPublishResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CommentPublishResult) GetSuccess() *react.CommentPublishResp {
	if !p.IsSetSuccess() {
		return CommentPublishResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CommentPublishResult) SetSuccess(x interface{}) {
	p.Success = x.(*react.CommentPublishResp)
}

func (p *CommentPublishResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CommentPublishResult) GetResult() interface{} {
	return p.Success
}

func commentListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(react.CommentListReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(react.CommentService).CommentList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CommentListArgs:
		success, err := handler.(react.CommentService).CommentList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CommentListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCommentListArgs() interface{} {
	return &CommentListArgs{}
}

func newCommentListResult() interface{} {
	return &CommentListResult{}
}

type CommentListArgs struct {
	Req *react.CommentListReq
}

func (p *CommentListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CommentListArgs) Unmarshal(in []byte) error {
	msg := new(react.CommentListReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CommentListArgs_Req_DEFAULT *react.CommentListReq

func (p *CommentListArgs) GetReq() *react.CommentListReq {
	if !p.IsSetReq() {
		return CommentListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CommentListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CommentListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CommentListResult struct {
	Success *react.CommentListResp
}

var CommentListResult_Success_DEFAULT *react.CommentListResp

func (p *CommentListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CommentListResult) Unmarshal(in []byte) error {
	msg := new(react.CommentListResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CommentListResult) GetSuccess() *react.CommentListResp {
	if !p.IsSetSuccess() {
		return CommentListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CommentListResult) SetSuccess(x interface{}) {
	p.Success = x.(*react.CommentListResp)
}

func (p *CommentListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CommentListResult) GetResult() interface{} {
	return p.Success
}

func commentDeleteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(react.CommentDeleteReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(react.CommentService).CommentDelete(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CommentDeleteArgs:
		success, err := handler.(react.CommentService).CommentDelete(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CommentDeleteResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCommentDeleteArgs() interface{} {
	return &CommentDeleteArgs{}
}

func newCommentDeleteResult() interface{} {
	return &CommentDeleteResult{}
}

type CommentDeleteArgs struct {
	Req *react.CommentDeleteReq
}

func (p *CommentDeleteArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CommentDeleteArgs) Unmarshal(in []byte) error {
	msg := new(react.CommentDeleteReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CommentDeleteArgs_Req_DEFAULT *react.CommentDeleteReq

func (p *CommentDeleteArgs) GetReq() *react.CommentDeleteReq {
	if !p.IsSetReq() {
		return CommentDeleteArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CommentDeleteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CommentDeleteArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CommentDeleteResult struct {
	Success *react.CommentDeleteResp
}

var CommentDeleteResult_Success_DEFAULT *react.CommentDeleteResp

func (p *CommentDeleteResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CommentDeleteResult) Unmarshal(in []byte) error {
	msg := new(react.CommentDeleteResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CommentDeleteResult) GetSuccess() *react.CommentDeleteResp {
	if !p.IsSetSuccess() {
		return CommentDeleteResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CommentDeleteResult) SetSuccess(x interface{}) {
	p.Success = x.(*react.CommentDeleteResp)
}

func (p *CommentDeleteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CommentDeleteResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CommentPublish(ctx context.Context, Req *react.CommentPublishReq) (r *react.CommentPublishResp, err error) {
	var _args CommentPublishArgs
	_args.Req = Req
	var _result CommentPublishResult
	if err = p.c.Call(ctx, "CommentPublish", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommentList(ctx context.Context, Req *react.CommentListReq) (r *react.CommentListResp, err error) {
	var _args CommentListArgs
	_args.Req = Req
	var _result CommentListResult
	if err = p.c.Call(ctx, "CommentList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommentDelete(ctx context.Context, Req *react.CommentDeleteReq) (r *react.CommentDeleteResp, err error) {
	var _args CommentDeleteArgs
	_args.Req = Req
	var _result CommentDeleteResult
	if err = p.c.Call(ctx, "CommentDelete", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
