// Code generated by hertz generator.

package main

import (
	"Tiktok/biz/middleware"
	router "Tiktok/biz/router"
	Rpc "Tiktok/biz/rpc"
	"Tiktok/internal/config"
	"Tiktok/pkg/logger"
	"os"

	"github.com/cloudwego/hertz/pkg/app/server"
	"go.uber.org/zap"
)

func main() {
	if err := config.LoadEnv(); err != nil {
		logger.Fatal("加载.env错误", zap.Error(err))
	}
	cfgPath := os.Getenv("CONFIG_PATH")
	logger.Info("loading configuration", zap.String("config_path", cfgPath))
	cfg, err := config.Load([]string{cfgPath})
	if err != nil {
		logger.Fatal("加载config.yaml错误", zap.Error(err))
	}
	if err := logger.InitLogger(cfg.Log.Level, "api", cfg.Log.Path); err != nil {
		logger.Fatal("初始化日志错误", zap.Error(err))
	}
	logger.Info("logger initialized", logger.WithServiceName("api"), zap.String("level", cfg.Log.Level))
	sentinelPath := os.Getenv("SENTINEL_PATH")
	logger.Info("loading sentinel", zap.String("sentinel_path", sentinelPath))
	err = config.LoadRules([]string{sentinelPath})
	if err != nil {
		logger.Fatal("加载sentinel rules错误", zap.Error(err))
	}

	Rpc.Init()

	h := server.Default(
		server.WithHostPorts(":8888"),
		server.WithMaxRequestBodySize(10*1024*1024),
	)
	h.Use(middleware.LoggingMiddleware())
	h.Use(middleware.AuthMiddleware)

	router.GeneratedRegister(h)

	h.Spin()
}
