// Code generated by hertz generator.

package main

import (
	"Tiktok/biz/handler/chat"
	"Tiktok/biz/handler/react"
	socialHandler "Tiktok/biz/handler/social"
	"Tiktok/biz/handler/video"
	"Tiktok/biz/middleware"
	"Tiktok/biz/router"
	Rpc "Tiktok/biz/rpc"
	ws "Tiktok/biz/service/chat"
	likeService "Tiktok/biz/service/react"
	socialService "Tiktok/biz/service/social"
	videoService "Tiktok/biz/service/video"
	"Tiktok/pkg/config"
	"Tiktok/pkg/dal/cache"
	"Tiktok/pkg/dal/dao"
	"os"

	"log"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/logger/accesslog"
	"github.com/joho/godotenv"
)

func main() {
	if err := godotenv.Load("/home/lai-long/Tiktok/.env"); err != nil {
		log.Println("load env error:", err)
	}
	cfgPath := os.Getenv("CONFIG_PATH")
	log.Printf("Loading configuration from %s", cfgPath)
	cfg, err := config.Load([]string{cfgPath})
	if err != nil {
		log.Fatal("加载config.yaml错误", err)
	}
	log.Println(cfg)
	sentinelPath := os.Getenv("SENTINEL_PATH")
	log.Printf("Loading sentinel from %s", sentinelPath)
	err = config.LoadRules([]string{sentinelPath})
	if err != nil {
		log.Fatal("加载sentinel rules错误", err)
	}

	rdb := cache.InitRedis()
	re := cache.NewRedis(rdb)
	defer func() {
		err := rdb.Close()
		if err != nil {
			log.Println("main redis close err", err)
		}
	}()

	ddb := dao.InitDb()
	defer func() {
		err := ddb.Close()
		if err != nil {
			log.Println("main database close err", err)
		}
	}()
	mysqlDb := dao.NewMySQLdb(ddb)
	Rpc.Init()

	videoSrv := videoService.NewVideoRepo(mysqlDb, re)
	videoHandler := video.NewVideoHandler(videoSrv)
	video.VideoPublish = videoHandler.VideoPublish
	video.VideoStream = videoHandler.VideoStream
	video.VideoSearch = videoHandler.VideoSearch
	video.VideoPopular = videoHandler.VideoPopular
	video.VideoList = videoHandler.VideoList

	socialSrv := socialService.NewSocialRepo(mysqlDb, mysqlDb)
	socialHdlr := socialHandler.NewSocialHandler(socialSrv)
	socialHandler.FollowingList = socialHdlr.FollowingList
	socialHandler.FollowerList = socialHdlr.FollowerList
	socialHandler.FriendList = socialHdlr.FriendList
	socialHandler.RelationAction = socialHdlr.RelationAction

	commentSrv := likeService.NewCommentService(mysqlDb)
	commentHandler := react.NewCommentHandler(commentSrv)
	react.CommentDelete = commentHandler.CommentDelete
	react.CommentPublish = commentHandler.CommentPublish
	react.CommentList = commentHandler.CommentList

	likeSrv := likeService.NewLikeRepo(mysqlDb, mysqlDb, mysqlDb, re)
	likeHandler := react.NewLikesHandler(likeSrv)
	react.LikeList = likeHandler.LikeList
	react.LikeAction = likeHandler.LikeAction

	wsService := ws.NewWebsocketService(mysqlDb, re)
	websocketService := chat.NewWebsocketSever(mysqlDb, re, wsService)
	chat.Websocket = websocketService.WebSocketHandler
	go wsService.Start()

	h := server.Default(
		server.WithHostPorts(":8888"),
		server.WithMaxRequestBodySize(10*1024*1024),
	)
	h.Use(accesslog.New())
	h.Use(middleware.AuthMiddleware)
	router.GeneratedRegister(h)

	h.Spin()
}
