// Code generated by Kitex v0.16.1. DO NOT EDIT.

package video

import (
	"context"

	"github.com/cloudwego/prutal"
)

type VideoInfo struct {
	ID           string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	UserID       string `protobuf:"bytes,2,opt,name=UserID" json:"UserID,omitempty"`
	Title        string `protobuf:"bytes,3,opt,name=Title" json:"Title,omitempty"`
	Description  string `protobuf:"bytes,4,opt,name=Description" json:"Description,omitempty"`
	CommentCount int64  `protobuf:"varint,5,opt,name=CommentCount" json:"CommentCount,omitempty"`
	CoverURL     string `protobuf:"bytes,6,opt,name=CoverURL" json:"CoverURL,omitempty"`
	CreatedAt    string `protobuf:"bytes,7,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
	LikeCount    int64  `protobuf:"varint,8,opt,name=LikeCount" json:"LikeCount,omitempty"`
	UpdatedAt    string `protobuf:"bytes,9,opt,name=UpdatedAt" json:"UpdatedAt,omitempty"`
	VideoURL     string `protobuf:"bytes,10,opt,name=VideoURL" json:"VideoURL,omitempty"`
	VisitCount   int64  `protobuf:"varint,11,opt,name=VisitCount" json:"VisitCount,omitempty"`
}

func (x *VideoInfo) Reset() { *x = VideoInfo{} }

func (x *VideoInfo) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *VideoInfo) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *VideoInfo) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *VideoInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *VideoInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VideoInfo) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *VideoInfo) GetCoverURL() string {
	if x != nil {
		return x.CoverURL
	}
	return ""
}

func (x *VideoInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VideoInfo) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *VideoInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *VideoInfo) GetVideoURL() string {
	if x != nil {
		return x.VideoURL
	}
	return ""
}

func (x *VideoInfo) GetVisitCount() int64 {
	if x != nil {
		return x.VisitCount
	}
	return 0
}

type VideoData struct {
	Items []*VideoInfo `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	Total int64        `protobuf:"varint,2,opt,name=Total" json:"Total,omitempty"`
}

func (x *VideoData) Reset() { *x = VideoData{} }

func (x *VideoData) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *VideoData) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *VideoData) GetItems() []*VideoInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *VideoData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type VideoPublishReq struct {
	Title       string `protobuf:"bytes,1,opt,name=Title" json:"Title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=Description" json:"Description,omitempty"`
	VideoURL    string `protobuf:"bytes,3,opt,name=VideoURL" json:"VideoURL,omitempty"`
	UserID      string `protobuf:"bytes,4,opt,name=UserID" json:"UserID,omitempty"`
}

func (x *VideoPublishReq) Reset() { *x = VideoPublishReq{} }

func (x *VideoPublishReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *VideoPublishReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *VideoPublishReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoPublishReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VideoPublishReq) GetVideoURL() string {
	if x != nil {
		return x.VideoURL
	}
	return ""
}

func (x *VideoPublishReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type VideoPublishResp struct {
	Code int32 `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
}

func (x *VideoPublishResp) Reset() { *x = VideoPublishResp{} }

func (x *VideoPublishResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *VideoPublishResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *VideoPublishResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type VideoListReq struct {
	UserId   string `protobuf:"bytes,1,opt,name=UserId" json:"UserId,omitempty"`
	PageNum  int64  `protobuf:"varint,2,opt,name=PageNum" json:"PageNum,omitempty"`
	PageSize int64  `protobuf:"varint,3,opt,name=PageSize" json:"PageSize,omitempty"`
}

func (x *VideoListReq) Reset() { *x = VideoListReq{} }

func (x *VideoListReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *VideoListReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *VideoListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VideoListReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *VideoListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type VideoListResp struct {
	Code int32      `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	Data *VideoData `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
}

func (x *VideoListResp) Reset() { *x = VideoListResp{} }

func (x *VideoListResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *VideoListResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *VideoListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VideoListResp) GetData() *VideoData {
	if x != nil {
		return x.Data
	}
	return nil
}

type VideoHotReq struct {
	PageNum  int64 `protobuf:"varint,1,opt,name=PageNum" json:"PageNum,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=PageSize" json:"PageSize,omitempty"`
}

func (x *VideoHotReq) Reset() { *x = VideoHotReq{} }

func (x *VideoHotReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *VideoHotReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *VideoHotReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *VideoHotReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type VideoHotResp struct {
	Code int32      `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	Data *VideoData `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
}

func (x *VideoHotResp) Reset() { *x = VideoHotResp{} }

func (x *VideoHotResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *VideoHotResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *VideoHotResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VideoHotResp) GetData() *VideoData {
	if x != nil {
		return x.Data
	}
	return nil
}

type VideoSearchReq struct {
	KeyWord  string `protobuf:"bytes,1,opt,name=KeyWord" json:"KeyWord,omitempty"`
	PageNum  int64  `protobuf:"varint,2,opt,name=PageNum" json:"PageNum,omitempty"`
	PageSize int64  `protobuf:"varint,3,opt,name=PageSize" json:"PageSize,omitempty"`
}

func (x *VideoSearchReq) Reset() { *x = VideoSearchReq{} }

func (x *VideoSearchReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *VideoSearchReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *VideoSearchReq) GetKeyWord() string {
	if x != nil {
		return x.KeyWord
	}
	return ""
}

func (x *VideoSearchReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *VideoSearchReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type VideoSearchResp struct {
	Code int32      `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	Data *VideoData `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
}

func (x *VideoSearchResp) Reset() { *x = VideoSearchResp{} }

func (x *VideoSearchResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *VideoSearchResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *VideoSearchResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VideoSearchResp) GetData() *VideoData {
	if x != nil {
		return x.Data
	}
	return nil
}

type VideoStreamReq struct {
}

func (x *VideoStreamReq) Reset() { *x = VideoStreamReq{} }

func (x *VideoStreamReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *VideoStreamReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type VideoStreamResp struct {
	Code int32      `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	Data *VideoData `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
}

func (x *VideoStreamResp) Reset() { *x = VideoStreamResp{} }

func (x *VideoStreamResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *VideoStreamResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *VideoStreamResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VideoStreamResp) GetData() *VideoData {
	if x != nil {
		return x.Data
	}
	return nil
}

type VideoService interface {
	VideoPublish(ctx context.Context, req *VideoPublishReq) (res *VideoPublishResp, err error)
	VideoList(ctx context.Context, req *VideoListReq) (res *VideoListResp, err error)
	VideoSearch(ctx context.Context, req *VideoSearchReq) (res *VideoSearchResp, err error)
	VideoPopular(ctx context.Context, req *VideoHotReq) (res *VideoHotResp, err error)
	VideoStream(ctx context.Context, req *VideoStreamReq) (res *VideoStreamResp, err error)
}
