// Code generated by hertz generator.

package chat

import (
	"Tiktok/biz/dal/cache"
	"Tiktok/biz/dal/dao"
	"Tiktok/biz/model/common"
	"Tiktok/biz/service"
	"Tiktok/pkg/utils"
	"context"
	"log"
	"net/http"

	chat "Tiktok/biz/model/chat"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/adaptor"
	"github.com/gorilla/websocket"
)

type WebsocketSever struct {
	db *dao.MySQLdb
	re *cache.Redis
}

func NewWebsocketSever(db *dao.MySQLdb, re *cache.Redis) *WebsocketSever {
	return &WebsocketSever{
		db: db,
		re: re,
	}
}

var (
	Websocket func(ctx context.Context, c *app.RequestContext)
)

// Websocket .
// @router /ws [GET]
func (m *WebsocketSever) WebSocketHandler(ctx context.Context, c *app.RequestContext) {
	userid, ok := ctx.Value("user_id").(string)
	if !ok || userid == "" {
		c.JSON(200, chat.WebsocketResp{Base: &common.Base{
			Code: 200,
			Msg:  "Unauthorized: user_id not found",
		}})
		return
	}
	log.Println("User connected:", userid)
	uid := userid
	req := new(chat.WebsocketReq)
	err := c.BindAndValidate(req)
	if err != nil {
		log.Println("BindAndValidate error:", err)
		c.JSON(200, chat.WebsocketResp{Base: &common.Base{
			Code: 0,
			Msg:  "Invalid request parameters",
		}})
		return
	}
	stdHandler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		conn, err := (&websocket.Upgrader{
			CheckOrigin: func(r *http.Request) bool {
				return true
			},
		}).Upgrade(w, r, nil)
		if err != nil {
			log.Println("WebSocket upgrade error:", err)
			http.Error(w, "Could not upgrade to WebSocket", http.StatusInternalServerError)
			return
		}
		client := &service.Client{
			ID:      utils.CreateId(uid, req.ToUserId),
			SendID:  utils.CreateId(req.ToUserId, uid),
			GroupId: req.GroupId,
			Socket:  conn,
			Send:    make(chan []byte, 128),
		}
		log.Println("WebSocket client:", client)
		service.Manager.Register <- client
		go client.Read()
		go client.Write()
	})
	wsAdaptor := adaptor.HertzHandler(stdHandler)
	wsAdaptor(ctx, c)
}
