// Code generated by hertz generator.

package react

import (
	"Tiktok/biz/model/common"
	react "Tiktok/biz/model/react"
	"context"
	"log"

	"Tiktok/pkg/consts"

	"github.com/cloudwego/hertz/pkg/app"
)

type CommentSever interface {
	CommentPublish(targetId, userId, content, targetType string) (int32, error)
	CommentList(targetId string, pageSize int64, pageNum int64) (int32, error, []*react.CommentInfo)
	CommentDelete(commentId string, target string, userId string, targetType string) (int32, error)
}
type CommentHandler struct {
	service CommentSever
}

func NewCommentHandler(service CommentSever) *CommentHandler {
	return &CommentHandler{
		service: service,
	}
}

var (
	CommentPublish func(ctx context.Context, c *app.RequestContext)
	CommentList    func(ctx context.Context, c *app.RequestContext)
	CommentDelete  func(ctx context.Context, c *app.RequestContext)
)

// CommentPublish .
// @router /comment/publish [POST]
func (h *CommentHandler) CommentPublish(ctx context.Context, c *app.RequestContext) {
	var req react.CommentPublishReq
	err := c.BindAndValidate(&req)
	if err != nil {
		resp := &react.CommentPublishResp{
			Base: &common.Base{Code: consts.ReactReqValidError, Msg: consts.GetErrorCodeMsg(consts.ReactReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	userId := ctx.Value("user_id").(string)
	code, err := h.service.CommentPublish(req.TargetAt, userId, req.Content, req.TargetType)
	if err != nil {
		log.Println("CommentPublish err:", err)
	}
	resp := &react.CommentPublishResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
	}
	c.JSON(200, resp)
}

// CommentList .
// @router /comment/list [GET]
func (h *CommentHandler) CommentList(ctx context.Context, c *app.RequestContext) {
	var req react.CommentListReq
	err := c.BindAndValidate(&req)
	if err != nil {
		resp := &react.CommentPublishResp{
			Base: &common.Base{Code: consts.ReactReqValidError, Msg: consts.GetErrorCodeMsg(consts.ReactReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	code, err, commentInfos := h.service.CommentList(req.TargetAt, req.PageSize, req.PageNum)
	resp := &react.CommentListResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data: &react.CommentData{Items: commentInfos},
	}
	c.JSON(200, resp)
}

// CommentDelete .
// @router /comment/delete [DELETE]
func (h *CommentHandler) CommentDelete(ctx context.Context, c *app.RequestContext) {
	var err error
	var req react.CommentDeleteReq
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := &react.CommentPublishResp{
			Base: &common.Base{Code: consts.ReactReqValidError, Msg: consts.GetErrorCodeMsg(consts.ReactReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	userId := ctx.Value("user_id").(string)
	code, err := h.service.CommentDelete(req.CommentId, req.TargetAt, userId, req.TargetType)
	if err != nil {
		log.Println("CommentDelete err:", err)
	}
	resp := new(react.CommentDeleteResp)
	resp.Base.Code = code
	resp.Base.Msg = consts.GetErrorCodeMsg(code)
	c.JSON(200, resp)
}
