// Code generated by hertz generator.

package react

import (
	"Tiktok/biz/model/common"
	react "Tiktok/biz/model/react"
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

type CommentSever interface {
	CommentPublish(targetId, userId, content, targetType string) (int, string)
	CommentList(targetId string, pageSize string, pageNum string) (int, string, []*react.CommentInfo, bool)
	CommentDelete(commentId string, target string, userId string, targetType string) (int, string)
}
type CommentHandler struct {
	service CommentSever
}

func NewCommentHandler(service CommentSever) *CommentHandler {
	return &CommentHandler{
		service: service,
	}
}

var (
	CommentPublish func(ctx context.Context, c *app.RequestContext)
	CommentList    func(ctx context.Context, c *app.RequestContext)
	CommentDelete  func(ctx context.Context, c *app.RequestContext)
)

// CommentPublish .
// @router /comment/publish [POST]
func (h *CommentHandler) CommentPublish(ctx context.Context, c *app.RequestContext) {
	var req react.CommentPublishReq
	err := c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	userId, _ := ctx.Value("user_id").(string)
	code, msg := h.service.CommentPublish(req.TargetAt, userId, req.Content, req.TargetType)
	resp := &react.CommentPublishResp{
		Base: &common.Base{Code: int32(code), Msg: msg},
	}
	c.JSON(consts.StatusOK, resp)
}

// CommentList .
// @router /comment/list [GET]
func (h *CommentHandler) CommentList(ctx context.Context, c *app.RequestContext) {
	var req react.CommentListReq
	err := c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	code, msg, commentInfos, _ := h.service.CommentList(req.TargetAt, req.PageSize, req.PageNum)
	resp := &react.CommentListResp{
		Base: &common.Base{Code: int32(code), Msg: msg},
		Data: &react.CommentData{Items: commentInfos},
	}
	c.JSON(consts.StatusOK, resp)
}

// CommentDelete .
// @router /comment/delete [DELETE]
func (h *CommentHandler) CommentDelete(ctx context.Context, c *app.RequestContext) {
	var err error
	var req react.CommentDeleteReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	userId, _ := ctx.Value("user_id").(string)
	code, msg := h.service.CommentDelete(req.CommentId, req.TargetAt, userId, req.TargetType)
	resp := new(react.CommentDeleteResp)
	resp.Base.Code = int32(code)
	resp.Base.Msg = msg
	c.JSON(consts.StatusOK, resp)
}
