// Code generated by hertz generator.

package react

import (
	"Tiktok/biz/model/common"
	"Tiktok/biz/model/react"
	react2 "Tiktok/kitex_gen/react"
	"Tiktok/pkg/logger"
	"Tiktok/pkg/utils"
	"context"

	Rpc "Tiktok/biz/rpc"
	"Tiktok/pkg/consts"

	"github.com/cloudwego/hertz/pkg/app"
	"go.uber.org/zap"
)

// CommentPublish .
// @router /comment/publish [POST]
func CommentPublish(ctx context.Context, c *app.RequestContext) {
	var req react.CommentPublishReq
	err := c.BindAndValidate(&req)
	if err != nil {
		resp := &react.CommentPublishResp{
			Base: &common.Base{Code: consts.ReactReqValidError, Msg: consts.GetErrorCodeMsg(consts.ReactReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	userId := utils.GetUserID(c)
	code, err := Rpc.CommentPublish(ctx, &react2.CommentPublishReq{
		TargetAt:   req.TargetAt,
		TargetType: req.TargetType,
		Content:    req.Content,
		UserID:     userId,
	})
	if err != nil {
		logger.Error("CommentPublish error", zap.Error(err))
	}
	resp := &react.CommentPublishResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
	}
	c.JSON(200, resp)
}

// CommentList .
// @router /comment/list [GET]
func CommentList(ctx context.Context, c *app.RequestContext) {
	var req react.CommentListReq
	err := c.BindAndValidate(&req)
	if err != nil {
		resp := &react.CommentListResp{
			Base: &common.Base{Code: consts.ReactReqValidError, Msg: consts.GetErrorCodeMsg(consts.ReactReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	code, data, err := Rpc.CommentList(ctx, &react2.CommentListReq{
		TargetAt: req.TargetAt,
		PageSize: req.PageSize,
		PageNum:  req.PageNum,
	})
	if err != nil {
		logger.Error("CommentList error", zap.Error(err))
	}
	resp := &react.CommentListResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data: data,
	}
	c.JSON(200, resp)
}

// CommentDelete .
// @router /comment/delete [DELETE]
func CommentDelete(ctx context.Context, c *app.RequestContext) {
	var req react.CommentDeleteReq
	err := c.BindAndValidate(&req)
	if err != nil {
		resp := &react.CommentDeleteResp{
			Base: &common.Base{Code: consts.ReactReqValidError, Msg: consts.GetErrorCodeMsg(consts.ReactReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	userId := utils.GetUserID(c)
	code, err := Rpc.CommentDelete(ctx, &react2.CommentDeleteReq{
		CommentId:  req.CommentId,
		TargetAt:   req.TargetAt,
		TargetType: req.TargetType,
		UserID:     userId,
	})
	if err != nil {
		logger.Error("CommentDelete error", zap.Error(err))
	}
	resp := &react.CommentDeleteResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
	}
	c.JSON(200, resp)
}
