// Code generated by hertz generator.

package react

import (
	"Tiktok/biz/model/common"
	"Tiktok/biz/model/video"
	"context"

	react "Tiktok/biz/model/react"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

type LikeSever interface {
	LikeAction(userId string, videoId string, action string, targetType string) (int, string)
	LikeList(userId string, pageNum string, pageSize string) (int, string, []*video.VideoInfo, bool)
}

type LikesHandler struct {
	likeService LikeSever
}

func NewLikesHandler(like LikeSever) *LikesHandler {
	return &LikesHandler{
		likeService: like,
	}
}

var (
	LikeAction func(ctx context.Context, c *app.RequestContext)
	LikeList   func(ctx context.Context, c *app.RequestContext)
)

// LikeAction .
// @router /like/action [POST]
func (h *LikesHandler) LikeAction(ctx context.Context, c *app.RequestContext) {
	//targetType 1、视频 2、评论
	var err error
	var req react.LikeActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	userId, _ := ctx.Value("user_id").(string)
	if req.TargetType == "" {
		c.JSON(200, react.LikeActionResp{Base: &common.Base{
			Code: 0,
			Msg:  "likeActionReq.TargetType err is null",
		}})
		return
	}
	code, msg := h.likeService.LikeAction(userId, req.TargetAt, req.ActionType, req.TargetType)
	resp := new(react.LikeActionResp)
	resp.Base.Code = int32(code)
	resp.Base.Msg = msg
	c.JSON(consts.StatusOK, resp)
}

// LikeList .
// @router /like/list [GET]
func (h *LikesHandler) LikeList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req react.LikeListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	code, msg, videoInfos, _ := h.likeService.LikeList(req.UserId, req.PageNum, req.PageSize)
	resp := &react.LikeListResp{
		Base: &common.Base{Code: int32(code), Msg: msg},
		Data: &react.LikeVideoData{Items: videoInfos, Total: int64(len(videoInfos))},
	}

	c.JSON(consts.StatusOK, resp)
}
