// Code generated by hertz generator.

package react

import (
	"Tiktok/biz/model/common"
	"Tiktok/biz/model/react"
	react2 "Tiktok/kitex_gen/react"
	"Tiktok/pkg/logger"
	"Tiktok/pkg/utils"
	"context"

	Rpc "Tiktok/biz/rpc"
	"Tiktok/pkg/consts"

	"github.com/cloudwego/hertz/pkg/app"
	"go.uber.org/zap"
)

// LikeAction .
// @router /like/action [POST]
func LikeAction(ctx context.Context, c *app.RequestContext) {
	var req react.LikeActionReq
	err := c.BindAndValidate(&req)
	if err != nil {
		resp := &react.LikeActionResp{
			Base: &common.Base{Code: consts.ReactReqValidError, Msg: consts.GetErrorCodeMsg(consts.ReactReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	userId := utils.GetUserID(c)
	if req.TargetType == "" {
		c.JSON(200, react.LikeActionResp{Base: &common.Base{
			Code: 0,
			Msg:  "likeActionReq.TargetType err is null",
		}})
		return
	}
	code, err := Rpc.LikeAction(ctx, &react2.LikeActionReq{
		TargetAt:   req.TargetAt,
		TargetType: req.TargetType,
		ActionType: req.ActionType,
		UserID:     userId,
	})
	if err != nil {
		logger.Error("likeService.LikeAction error", zap.Error(err))
	}
	resp := &react.LikeActionResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
	}
	c.JSON(200, resp)
}

// LikeList .
// @router /like/list [GET]
func LikeList(ctx context.Context, c *app.RequestContext) {
	var req react.LikeListReq
	err := c.BindAndValidate(&req)
	if err != nil {
		resp := &react.LikeListResp{
			Base: &common.Base{Code: consts.ReactReqValidError, Msg: consts.GetErrorCodeMsg(consts.ReactReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	code, data, err := Rpc.LikeList(ctx, &react2.LikeListReq{
		UserId:   req.UserId,
		PageNum:  req.PageNum,
		PageSize: req.PageSize,
	})
	if err != nil {
		logger.Error("likeService.LikeList error", zap.Error(err))
	}
	resp := &react.LikeListResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data: data,
	}
	c.JSON(200, resp)
}
