// Code generated by hertz generator.

package react

import (
	"Tiktok/biz/model/common"
	"Tiktok/biz/model/video"
	"context"
	"log"

	react "Tiktok/biz/model/react"

	"Tiktok/pkg/consts"

	"github.com/cloudwego/hertz/pkg/app"
)

type LikeSever interface {
	LikeAction(userId string, videoId string, action string, targetType string) (int32, error)
	LikeList(userId string, pageNum int64, pageSize int64) (int32, error, []*video.VideoInfo)
}

type LikesHandler struct {
	likeService LikeSever
}

func NewLikesHandler(like LikeSever) *LikesHandler {
	return &LikesHandler{
		likeService: like,
	}
}

var (
	LikeAction func(ctx context.Context, c *app.RequestContext)
	LikeList   func(ctx context.Context, c *app.RequestContext)
)

// LikeAction .
// @router /like/action [POST]
func (h *LikesHandler) LikeAction(ctx context.Context, c *app.RequestContext) {
	//targetType 1、视频 2、评论
	var err error
	var req react.LikeActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := &react.CommentPublishResp{
			Base: &common.Base{Code: consts.ReactReqValidError, Msg: consts.GetErrorCodeMsg(consts.ReactReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	userId := ctx.Value("user_id").(string)
	if req.TargetType == "" {
		c.JSON(200, react.LikeActionResp{Base: &common.Base{
			Code: 0,
			Msg:  "likeActionReq.TargetType err is null",
		}})
		return
	}
	code, err := h.likeService.LikeAction(userId, req.TargetAt, req.ActionType, req.TargetType)
	if err != nil {
		log.Println("likeService.LikeAction:", err)
	}
	resp := new(react.LikeActionResp)
	resp.Base = &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)}
	c.JSON(200, resp)
}

// LikeList .
// @router /like/list [GET]
func (h *LikesHandler) LikeList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req react.LikeListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := &react.CommentPublishResp{
			Base: &common.Base{Code: consts.ReactReqValidError, Msg: consts.GetErrorCodeMsg(consts.ReactReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	code, err, videoInfos := h.likeService.LikeList(req.UserId, req.PageNum, req.PageSize)
	if err != nil {
		log.Println("likeService.LikeList:", err)
	}
	resp := &react.LikeListResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data: &react.LikeVideoData{Items: videoInfos, Total: int64(len(videoInfos))},
	}
	c.JSON(200, resp)
}
