// Code generated by hertz generator.

package video

import (
	"Tiktok/biz/model/common"
	"context"
	"log"
	"mime/multipart"

	video "Tiktok/biz/model/video"

	"Tiktok/pkg/consts"

	"github.com/cloudwego/hertz/pkg/app"
)

type VideoSever interface {
	VideoPublish(video *video.VideoInfo, data *multipart.FileHeader, ctx context.Context) (int32, error)
	VideoList(userId string, pageSize int64, pageNum int64) (int32, error, []*video.VideoInfo)
	VideoSearch(keyword string, pageNun, pageSize int64) (int32, error, []*video.VideoInfo)
	VideoPopular(ctx context.Context, pageNum int64, pageSize int64) (int32, error, []*video.VideoInfo)
	VideoStream() (int32, error, []*video.VideoInfo)
}
type VideoHandler struct {
	videoService VideoSever
}

func NewVideoHandler(videoService VideoSever) *VideoHandler {
	return &VideoHandler{videoService: videoService}
}

var (
	VideoPublish func(ctx context.Context, c *app.RequestContext)
	VideoList    func(ctx context.Context, c *app.RequestContext)
	VideoSearch  func(ctx context.Context, c *app.RequestContext)
	VideoPopular func(ctx context.Context, c *app.RequestContext)
	VideoStream  func(ctx context.Context, c *app.RequestContext)
)

// VideoPublish .
// @router /video/publish [POST]
func (h *VideoHandler) VideoPublish(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoPublishReq
	err = c.BindAndValidate(&req)
	if err != nil {
		log.Println("video publish  bind err:", err)
		resp := &video.VideoPublishResp{
			Base: &common.Base{Code: consts.VideoReqValidError, Msg: consts.GetErrorCodeMsg(consts.VideoReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	data, _ := c.FormFile("data")
	userId, _ := c.Value("user_id").(string)
	videoInfo := &video.VideoInfo{
		UserID:      userId,
		Title:       req.Title,
		Description: req.Description,
	}
	code, err := h.videoService.VideoPublish(videoInfo, data, ctx)
	if err != nil {
		log.Println("video publish err:", err)
	}
	resp := new(video.VideoPublishResp)
	resp.Base = &common.Base{
		Code: code,
		Msg:  consts.GetErrorCodeMsg(code),
	}
	c.JSON(200, resp)
}

// VideoList .
// @router /video/list [GET]
func (h *VideoHandler) VideoList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		log.Println("video list  bind err:", err)
		resp := &video.VideoPublishResp{
			Base: &common.Base{Code: consts.VideoReqValidError, Msg: consts.GetErrorCodeMsg(consts.VideoReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	code, err, videoInfos := h.videoService.VideoList(req.UserId, req.PageSize, req.PageNum)
	if err != nil {
		log.Println("video list err:", err)
	}
	resp := &video.VideoListResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data: &video.VideoData{Items: videoInfos, Total: int64(len(videoInfos))},
	}
	c.JSON(200, resp)
}

// VideoSearch .
// @router /video/search [POST]
func (h *VideoHandler) VideoSearch(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoSearchReq
	err = c.BindAndValidate(&req)
	if err != nil {
		log.Println("video search  bind err:", err)
		resp := &video.VideoPublishResp{
			Base: &common.Base{Code: consts.VideoReqValidError, Msg: consts.GetErrorCodeMsg(consts.VideoReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	code, err, videoInfos := h.videoService.VideoSearch(req.KeyWord, req.PageNum, req.PageSize)
	if err != nil {
		log.Println("video search err:", err)
	}
	resp := &video.VideoListResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data: &video.VideoData{Items: videoInfos, Total: int64(len(videoInfos))},
	}
	c.JSON(200, resp)
}

// VideoPopular .
// @router /video/popular [GET]
func (h *VideoHandler) VideoPopular(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoHotReq
	err = c.BindAndValidate(&req)
	if err != nil {
		log.Println("video popular  bind err:", err)
		resp := &video.VideoPublishResp{
			Base: &common.Base{Code: consts.VideoReqValidError, Msg: consts.GetErrorCodeMsg(consts.VideoReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	code, err, videoInfos := h.videoService.VideoPopular(ctx, req.PageNum, req.PageSize)
	if err != nil {
		log.Println("video popular err:", err)
	}
	resp := &video.VideoListResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data: &video.VideoData{Items: videoInfos, Total: int64(len(videoInfos))},
	}
	c.JSON(200, resp)
}

// VideoStream .
// @router /video/feed [GET]
func (h *VideoHandler) VideoStream(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoStreamReq
	err = c.BindAndValidate(&req)
	if err != nil {
		log.Println("video stream  bind err:", err)
		resp := &video.VideoPublishResp{
			Base: &common.Base{Code: consts.VideoReqValidError, Msg: consts.GetErrorCodeMsg(consts.VideoReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	code, err, videoInfos := h.videoService.VideoStream()
	if err != nil {
		log.Println("video stream err:", err)
	}
	resp := &video.VideoListResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data: &video.VideoData{Items: videoInfos, Total: int64(len(videoInfos))},
	}
	c.JSON(200, resp)
}
