// Code generated by hertz generator.

package video

import (
	"Tiktok/biz/model/common"
	video "Tiktok/biz/model/video"
	Rpc "Tiktok/biz/rpc"
	video2 "Tiktok/kitex_gen/video"
	"Tiktok/pkg/config"
	"Tiktok/pkg/logger"
	"Tiktok/pkg/utils"
	"context"
	"path/filepath"

	"Tiktok/pkg/consts"

	"github.com/alibaba/sentinel-golang/api"
	"github.com/cloudwego/hertz/pkg/app"
	"go.uber.org/zap"
)

// VideoPublish .
// @router /video/publish [POST]
func VideoPublish(ctx context.Context, c *app.RequestContext) {
	userID := utils.GetUserID(c)
	var req video.VideoPublishReq
	err := c.BindAndValidate(&req)
	if err != nil {
		logger.Warn("video publish binding failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("action", "video_publish"),
			zap.Error(err))
		resp := &video.VideoPublishResp{
			Base: &common.Base{Code: consts.VideoReqValidError, Msg: consts.GetErrorCodeMsg(consts.VideoReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	data, err := c.FormFile("data")
	if err != nil {
		logger.Error("video publish FormFile failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("action", "video_publish"),
			zap.Error(err))
		resp := &video.VideoPublishResp{
			Base: &common.Base{Code: consts.VideoReqValidError, Msg: consts.GetErrorCodeMsg(consts.VideoReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	if userID == "" {
		logger.Warn("video publish user id not found",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("action", "video_publish"))
		resp := &video.VideoPublishResp{
			Base: &common.Base{Code: consts.VideoReqValidError, Msg: consts.GetErrorCodeMsg(consts.VideoReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	logger.Info("video publish started",
		logger.WithServiceName("api"),
		logger.WithUserID(userID),
		logger.WithField("filename", data.Filename),
		logger.WithField("action", "video_publish"))

	dataFile, err := data.Open()
	if err != nil {
		logger.Error("video publish file open failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("filename", data.Filename),
			logger.WithField("action", "video_publish"),
			zap.Error(err))
		c.JSON(200, &video.VideoPublishResp{
			Base: &common.Base{Code: consts.FileError, Msg: consts.GetErrorCodeMsg(consts.FileError)},
		})
		return
	}
	filename := utils.IDGenerate()
	code, err := utils.SaveUploadFile(dataFile, config.Cfg.Path.VideoPath, filename+filepath.Ext(data.Filename))
	_ = dataFile.Close()
	if err != nil {
		logger.Error("video publish save file failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("filename", data.Filename),
			logger.WithField("action", "video_publish"),
			zap.Error(err))
		c.JSON(200, &video.VideoPublishResp{
			Base: &common.Base{
				Code: code,
				Msg:  consts.GetErrorCodeMsg(code),
			},
		})
		return
	}
	rpcReq := &video2.VideoPublishReq{
		Title:       req.Title,
		Description: req.Description,
		VideoURL:    config.Cfg.Path.VideoPath + filename + filepath.Ext(data.Filename),
		UserID:      userID,
	}
	code, err = Rpc.VideoPublish(ctx, rpcReq)
	if err != nil {
		logger.Error("video publish RPC failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("video_url", rpcReq.VideoURL),
			logger.WithField("action", "video_publish"),
			zap.Error(err))
		resp := &video.VideoPublishResp{
			Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		}
		c.JSON(200, resp)
		return
	}
	if code == 0 {
		logger.Info("video publish success",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("video_url", rpcReq.VideoURL),
			logger.WithField("title", req.Title),
			logger.WithField("action", "video_publish"))
	}
	resp := new(video.VideoPublishResp)
	resp.Base = &common.Base{
		Code: code,
		Msg:  consts.GetErrorCodeMsg(code),
	}
	c.JSON(200, resp)
}

// VideoList .
// @router /video/list [GET]
func VideoList(ctx context.Context, c *app.RequestContext) {
	userID := utils.GetUserID(c)
	var req video.VideoListReq
	err := c.BindAndValidate(&req)
	if err != nil {
		logger.Warn("video list binding failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("action", "video_list"),
			zap.Error(err))
		resp := &video.VideoListResp{
			Base: &common.Base{Code: consts.VideoReqValidError, Msg: consts.GetErrorCodeMsg(consts.VideoReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	rpcReq := &video2.VideoListReq{
		UserId:   req.UserId,
		PageNum:  req.PageNum,
		PageSize: req.PageSize,
	}
	code, data, err := Rpc.VideoList(ctx, rpcReq)
	if err != nil {
		logger.Error("video list query failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("target_user_id", req.UserId),
			logger.WithField("action", "video_list"),
			zap.Error(err))
		resp := &video.VideoListResp{
			Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		}
		c.JSON(200, resp)
		return
	}
	resp := &video.VideoListResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data: data,
	}
	c.JSON(200, resp)
}

// VideoSearch .
// @router /video/search [POST]
func VideoSearch(ctx context.Context, c *app.RequestContext) {
	userID := utils.GetUserID(c)
	var req video.VideoSearchReq
	err := c.BindAndValidate(&req)
	if err != nil {
		logger.Warn("video search binding failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("action", "video_search"),
			zap.Error(err))
		resp := &video.VideoListResp{
			Base: &common.Base{Code: consts.VideoReqValidError, Msg: consts.GetErrorCodeMsg(consts.VideoReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	rpcReq := &video2.VideoSearchReq{
		KeyWord:  req.KeyWord,
		PageNum:  req.PageNum,
		PageSize: req.PageSize,
	}
	code, data, err := Rpc.VideoSearch(ctx, rpcReq)
	if err != nil {
		logger.Error("video search query failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("keyword", req.KeyWord),
			logger.WithField("action", "video_search"),
			zap.Error(err))
		resp := &video.VideoListResp{
			Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		}
		c.JSON(200, resp)
		return
	}
	resp := &video.VideoListResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data: data,
	}
	c.JSON(200, resp)
}

// VideoPopular .
// @router /video/popular [GET]
func VideoPopular(ctx context.Context, c *app.RequestContext) {
	userID := utils.GetUserID(c)
	entry, blockErr := api.Entry("/video/popular")
	if blockErr != nil {
		logger.Warn("video popular sentinel blocked",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("action", "video_popular"))
		c.JSON(200, &video.VideoListResp{Base: &common.Base{Code: consts.SentinelBlock, Msg: consts.GetErrorCodeMsg(consts.SentinelBlock)}})
		return
	}
	defer entry.Exit()

	var req video.VideoHotReq
	err := c.BindAndValidate(&req)
	if err != nil {
		logger.Warn("video popular binding failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("action", "video_popular"),
			zap.Error(err))
		resp := &video.VideoListResp{
			Base: &common.Base{Code: consts.VideoReqValidError, Msg: consts.GetErrorCodeMsg(consts.VideoReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	rpcReq := &video2.VideoHotReq{
		PageNum:  req.PageNum,
		PageSize: req.PageSize,
	}
	code, data, err := Rpc.VideoPopular(ctx, rpcReq)
	if err != nil {
		logger.Error("video popular query failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("action", "video_popular"),
			zap.Error(err))
		resp := &video.VideoListResp{
			Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		}
		c.JSON(200, resp)
		return
	}
	resp := &video.VideoListResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data: data,
	}
	c.JSON(200, resp)
}

// VideoStream .
// @router /video/feed [GET]
func VideoStream(ctx context.Context, c *app.RequestContext) {
	userID := utils.GetUserID(c)
	entry, blockErr := api.Entry("/video/feed")
	if blockErr != nil {
		logger.Warn("video stream sentinel blocked",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("action", "video_stream"))
		c.JSON(200, &video.VideoListResp{Base: &common.Base{Code: consts.SentinelBlock, Msg: consts.GetErrorCodeMsg(consts.SentinelBlock)}})
		return
	}
	defer entry.Exit()

	var req video.VideoStreamReq
	err := c.BindAndValidate(&req)
	if err != nil {
		logger.Warn("video stream binding failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("action", "video_stream"),
			zap.Error(err))
		resp := &video.VideoListResp{
			Base: &common.Base{Code: consts.VideoReqValidError, Msg: consts.GetErrorCodeMsg(consts.VideoReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	rpcReq := &video2.VideoStreamReq{}
	code, data, err := Rpc.VideoStream(ctx, rpcReq)
	if err != nil {
		logger.Error("video stream query failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("action", "video_stream"),
			zap.Error(err))
		resp := &video.VideoListResp{
			Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		}
		c.JSON(200, resp)
		return
	}
	resp := &video.VideoListResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data: data,
	}
	c.JSON(200, resp)
}
