// Code generated by Kitex v0.16.1. DO NOT EDIT.

package mfaservice

import (
	mfa "Tiktok/kitex_gen/mfa"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	MfaQrcode(ctx context.Context, Req *mfa.MfaQrcodeReq, callOptions ...callopt.Option) (r *mfa.MfaQrcodeResp, err error)
	MfaBind(ctx context.Context, Req *mfa.MfaBindReq, callOptions ...callopt.Option) (r *mfa.MfaBindResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMfaServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMfaServiceClient struct {
	*kClient
}

func (p *kMfaServiceClient) MfaQrcode(ctx context.Context, Req *mfa.MfaQrcodeReq, callOptions ...callopt.Option) (r *mfa.MfaQrcodeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MfaQrcode(ctx, Req)
}

func (p *kMfaServiceClient) MfaBind(ctx context.Context, Req *mfa.MfaBindReq, callOptions ...callopt.Option) (r *mfa.MfaBindResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MfaBind(ctx, Req)
}
