// Code generated by Kitex v0.16.1. DO NOT EDIT.

package mfaservice

import (
	mfa "Tiktok/kitex_gen/mfa"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"MfaQrcode": kitex.NewMethodInfo(
		mfaQrcodeHandler,
		newMfaQrcodeArgs,
		newMfaQrcodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"MfaBind": kitex.NewMethodInfo(
		mfaBindHandler,
		newMfaBindArgs,
		newMfaBindResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"MfaConfirm": kitex.NewMethodInfo(
		mfaConfirmHandler,
		newMfaConfirmArgs,
		newMfaConfirmResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	mfaServiceServiceInfo                = NewServiceInfo()
	mfaServiceServiceInfoForClient       = NewServiceInfoForClient()
	mfaServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return mfaServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return mfaServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return mfaServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "MfaService"
	handlerType := (*mfa.MfaService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "mfa",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func mfaQrcodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(mfa.MfaQrcodeReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(mfa.MfaService).MfaQrcode(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *MfaQrcodeArgs:
		success, err := handler.(mfa.MfaService).MfaQrcode(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*MfaQrcodeResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newMfaQrcodeArgs() interface{} {
	return &MfaQrcodeArgs{}
}

func newMfaQrcodeResult() interface{} {
	return &MfaQrcodeResult{}
}

type MfaQrcodeArgs struct {
	Req *mfa.MfaQrcodeReq
}

func (p *MfaQrcodeArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *MfaQrcodeArgs) Unmarshal(in []byte) error {
	msg := new(mfa.MfaQrcodeReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var MfaQrcodeArgs_Req_DEFAULT *mfa.MfaQrcodeReq

func (p *MfaQrcodeArgs) GetReq() *mfa.MfaQrcodeReq {
	if !p.IsSetReq() {
		return MfaQrcodeArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *MfaQrcodeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MfaQrcodeArgs) GetFirstArgument() interface{} {
	return p.Req
}

type MfaQrcodeResult struct {
	Success *mfa.MfaQrcodeResp
}

var MfaQrcodeResult_Success_DEFAULT *mfa.MfaQrcodeResp

func (p *MfaQrcodeResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *MfaQrcodeResult) Unmarshal(in []byte) error {
	msg := new(mfa.MfaQrcodeResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *MfaQrcodeResult) GetSuccess() *mfa.MfaQrcodeResp {
	if !p.IsSetSuccess() {
		return MfaQrcodeResult_Success_DEFAULT
	}
	return p.Success
}

func (p *MfaQrcodeResult) SetSuccess(x interface{}) {
	p.Success = x.(*mfa.MfaQrcodeResp)
}

func (p *MfaQrcodeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MfaQrcodeResult) GetResult() interface{} {
	return p.Success
}

func mfaBindHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(mfa.MfaBindReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(mfa.MfaService).MfaBind(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *MfaBindArgs:
		success, err := handler.(mfa.MfaService).MfaBind(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*MfaBindResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newMfaBindArgs() interface{} {
	return &MfaBindArgs{}
}

func newMfaBindResult() interface{} {
	return &MfaBindResult{}
}

type MfaBindArgs struct {
	Req *mfa.MfaBindReq
}

func (p *MfaBindArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *MfaBindArgs) Unmarshal(in []byte) error {
	msg := new(mfa.MfaBindReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var MfaBindArgs_Req_DEFAULT *mfa.MfaBindReq

func (p *MfaBindArgs) GetReq() *mfa.MfaBindReq {
	if !p.IsSetReq() {
		return MfaBindArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *MfaBindArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MfaBindArgs) GetFirstArgument() interface{} {
	return p.Req
}

type MfaBindResult struct {
	Success *mfa.MfaBindResp
}

var MfaBindResult_Success_DEFAULT *mfa.MfaBindResp

func (p *MfaBindResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *MfaBindResult) Unmarshal(in []byte) error {
	msg := new(mfa.MfaBindResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *MfaBindResult) GetSuccess() *mfa.MfaBindResp {
	if !p.IsSetSuccess() {
		return MfaBindResult_Success_DEFAULT
	}
	return p.Success
}

func (p *MfaBindResult) SetSuccess(x interface{}) {
	p.Success = x.(*mfa.MfaBindResp)
}

func (p *MfaBindResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MfaBindResult) GetResult() interface{} {
	return p.Success
}

func mfaConfirmHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(mfa.MfaConfirmReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(mfa.MfaService).MfaConfirm(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *MfaConfirmArgs:
		success, err := handler.(mfa.MfaService).MfaConfirm(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*MfaConfirmResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newMfaConfirmArgs() interface{} {
	return &MfaConfirmArgs{}
}

func newMfaConfirmResult() interface{} {
	return &MfaConfirmResult{}
}

type MfaConfirmArgs struct {
	Req *mfa.MfaConfirmReq
}

func (p *MfaConfirmArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *MfaConfirmArgs) Unmarshal(in []byte) error {
	msg := new(mfa.MfaConfirmReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var MfaConfirmArgs_Req_DEFAULT *mfa.MfaConfirmReq

func (p *MfaConfirmArgs) GetReq() *mfa.MfaConfirmReq {
	if !p.IsSetReq() {
		return MfaConfirmArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *MfaConfirmArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MfaConfirmArgs) GetFirstArgument() interface{} {
	return p.Req
}

type MfaConfirmResult struct {
	Success *mfa.MfaConfirmResp
}

var MfaConfirmResult_Success_DEFAULT *mfa.MfaConfirmResp

func (p *MfaConfirmResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *MfaConfirmResult) Unmarshal(in []byte) error {
	msg := new(mfa.MfaConfirmResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *MfaConfirmResult) GetSuccess() *mfa.MfaConfirmResp {
	if !p.IsSetSuccess() {
		return MfaConfirmResult_Success_DEFAULT
	}
	return p.Success
}

func (p *MfaConfirmResult) SetSuccess(x interface{}) {
	p.Success = x.(*mfa.MfaConfirmResp)
}

func (p *MfaConfirmResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MfaConfirmResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) MfaQrcode(ctx context.Context, Req *mfa.MfaQrcodeReq) (r *mfa.MfaQrcodeResp, err error) {
	var _args MfaQrcodeArgs
	_args.Req = Req
	var _result MfaQrcodeResult
	if err = p.c.Call(ctx, "MfaQrcode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MfaBind(ctx context.Context, Req *mfa.MfaBindReq) (r *mfa.MfaBindResp, err error) {
	var _args MfaBindArgs
	_args.Req = Req
	var _result MfaBindResult
	if err = p.c.Call(ctx, "MfaBind", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MfaConfirm(ctx context.Context, Req *mfa.MfaConfirmReq) (r *mfa.MfaConfirmResp, err error) {
	var _args MfaConfirmArgs
	_args.Req = Req
	var _result MfaConfirmResult
	if err = p.c.Call(ctx, "MfaConfirm", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
