// Code generated by hertz generator.

package user

import (
	"Tiktok/biz/model/common"
	"Tiktok/pkg/logger"
	"Tiktok/pkg/utils"
	"context"
	"path/filepath"

	"Tiktok/biz/model/user"
	Rpc "Tiktok/biz/rpc"
	user2 "Tiktok/kitex_gen/user"
	"Tiktok/pkg/consts"

	"github.com/cloudwego/hertz/pkg/app"
	"go.uber.org/zap"
)

// UserRegister .
// @router /user/register [POST]
func UserRegister(ctx context.Context, c *app.RequestContext) {
	var req user.RegisterReq
	err := c.BindAndValidate(&req)
	if err != nil {
		code := consts.UserReqValidError
		resp := &user.RegisterResp{
			Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		}
		c.JSON(200, resp)
		logger.Warn("user register binding failed",
			logger.WithServiceName("api"),
			logger.WithField("username", req.UserName),
			logger.WithField("action", "register"),
			zap.Error(err))
		return
	}
	code, err := Rpc.RegisterRpc(ctx, &user2.RegisterReq{
		UserName: req.UserName,
		Password: req.Password,
	})
	if err != nil {
		logger.Error("user register failed",
			logger.WithServiceName("api"),
			logger.WithField("username", req.UserName),
			logger.WithField("action", "register"),
			zap.Error(err))
	}
	resp := new(user.RegisterResp)
	resp.Base = &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)}
	c.JSON(200, resp)
}

// UserLogin .
// @router /user/login [POST]
func UserLogin(ctx context.Context, c *app.RequestContext) {
	var req user.LoginReq
	err := c.BindAndValidate(&req)
	if err != nil {
		logger.Warn("user login binding failed",
			logger.WithServiceName("api"),
			logger.WithField("username", req.UserName),
			logger.WithField("action", "login"),
			zap.Error(err))
		resp := &user.LoginResp{
			Base: &common.Base{Code: consts.UserReqValidError, Msg: consts.GetErrorCodeMsg(consts.UserReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	code, userInfo, reToken, acToken, err := Rpc.LoginRpc(ctx, &user2.LoginReq{
		UserName: req.UserName,
		Password: req.Password,
		Code:     req.Code,
	})
	if err != nil {
		logger.Error("user login failed",
			logger.WithServiceName("api"),
			logger.WithField("username", req.UserName),
			logger.WithField("action", "login"),
			zap.Error(err))
	}
	if code == 0 {
		logger.Info("user login success",
			logger.WithServiceName("api"),
			logger.WithField("username", req.UserName),
			logger.WithField("action", "login"))
	}
	resp := &user.LoginResp{
		Base:         &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data:         userInfo,
		RefreshToken: reToken,
		AccessToken:  acToken,
	}
	c.JSON(200, resp)
}

// UserInfo .
// @router /user/info [GET]
func UserInfo(ctx context.Context, c *app.RequestContext) {
	userID := utils.GetUserID(c)
	var req user.UserInfoReq
	err := c.BindAndValidate(&req)
	if err != nil {
		logger.Warn("user info binding failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("action", "get_user_info"),
			zap.Error(err))
		resp := &user.UserInfoResp{
			Base: &common.Base{Code: consts.UserReqValidError, Msg: consts.GetErrorCodeMsg(consts.UserReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	code, userInfo, err := Rpc.UserInfoRpc(ctx, &user2.UserInfoReq{UserId: req.UserId})
	if err != nil {
		logger.Error("user info query failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("target_user_id", req.UserId),
			logger.WithField("action", "get_user_info"),
			zap.Error(err))
	}
	resp := &user.UserInfoResp{
		Base: &common.Base{
			Code: code,
			Msg:  consts.GetErrorCodeMsg(code),
		},
		Data: userInfo,
	}
	c.JSON(200, resp)
}

// UserAvatar .
// @router /user/avatar/upload [PUT]
func UserAvatar(ctx context.Context, c *app.RequestContext) {
	userID := utils.GetUserID(c)
	var req user.UserAvatarReq
	err := c.BindAndValidate(&req)
	if err != nil {
		logger.Warn("user avatar upload binding failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("action", "upload_avatar"),
			zap.Error(err))
		resp := &user.UserAvatarResp{
			Base: &common.Base{Code: consts.UserReqValidError, Msg: consts.GetErrorCodeMsg(consts.UserReqValidError)},
		}
		c.JSON(200, resp)
		return
	}

	data, err := c.FormFile("data")
	if err != nil {
		logger.Error("user avatar upload FormFile failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("action", "upload_avatar"),
			zap.Error(err))
		resp := &user.UserAvatarResp{
			Base: &common.Base{Code: consts.UserReqValidError, Msg: consts.GetErrorCodeMsg(consts.UserReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	file, err := data.Open()
	if err != nil {
		logger.Error("user avatar upload file open failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("filename", data.Filename),
			logger.WithField("action", "upload_avatar"),
			zap.Error(err))
		resp := &user.UserAvatarResp{
			Base: &common.Base{Code: consts.FileError, Msg: consts.GetErrorCodeMsg(consts.FileError)},
			Data: nil,
		}
		c.JSON(200, resp)
		return
	}
	defer func() {
		err = file.Close()
		if err != nil {
			logger.Error("file close error",
				logger.WithServiceName("api"),
				logger.WithUserID(userID),
				logger.WithField("action", "upload_avatar"),
				zap.Error(err))
		}
	}()
	ok, err := utils.IsImage(file)
	if err != nil {
		logger.Error("user avatar upload IsImage check failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("filename", data.Filename),
			logger.WithField("action", "upload_avatar"),
			zap.Error(err))
		resp := &user.UserAvatarResp{
			Base: &common.Base{Code: consts.FileError, Msg: consts.GetErrorCodeMsg(consts.FileError)},
			Data: nil,
		}
		c.JSON(200, resp)
		return
	}
	if !ok {
		logger.Warn("user avatar upload invalid file type",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("filename", data.Filename),
			logger.WithField("action", "upload_avatar"))
		resp := &user.UserAvatarResp{
			Base: &common.Base{Code: consts.ImageFalse, Msg: consts.GetErrorCodeMsg(consts.FileError)},
			Data: nil,
		}
		c.JSON(200, resp)
		return
	}
	filename := utils.IDGenerate()
	ext := filepath.Ext(data.Filename)
	objectName := "avatar/" + filename + ext

	_, seekErr := file.Seek(0, 0)
	if seekErr != nil {
		logger.Error("user avatar upload file seek failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("action", "upload_avatar"),
			zap.Error(seekErr))
		resp := &user.UserAvatarResp{
			Base: &common.Base{Code: consts.FileError, Msg: consts.GetErrorCodeMsg(consts.FileError)},
			Data: nil,
		}
		c.JSON(200, resp)
		return
	}

	qiniuKey, uploadErr := utils.UploadToQiNiu(file, objectName, data.Filename)
	if uploadErr != nil {
		logger.Error("user avatar upload to qiniu failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("object_name", objectName),
			logger.WithField("action", "upload_avatar"),
			zap.Error(uploadErr))
		resp := &user.UserAvatarResp{
			Base: &common.Base{Code: consts.FileError, Msg: consts.GetErrorCodeMsg(consts.FileError)},
			Data: nil,
		}
		c.JSON(200, resp)
		return
	}

	code, userInfo, err := Rpc.UserAvatarRpc(ctx, &user2.UserAvatarReq{
		AvatarURL: qiniuKey,
		UserID:    userID,
	})
	if err != nil {
		logger.Error("user avatar upload save failed",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("avatar_url", qiniuKey),
			logger.WithField("action", "upload_avatar"),
			zap.Error(err))
	}
	if code == 0 {
		logger.Info("user avatar upload success",
			logger.WithServiceName("api"),
			logger.WithUserID(userID),
			logger.WithField("avatar_url", qiniuKey),
			logger.WithField("action", "upload_avatar"))
	}
	resp := &user.UserAvatarResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data: userInfo,
	}
	c.JSON(200, resp)
}

// RefreshToken .
// @router /user/refresh [POST]
func RefreshToken(ctx context.Context, c *app.RequestContext) {
	var req user.RefreshTokenReq
	err := c.BindAndValidate(&req)
	if err != nil {
		logger.Warn("refresh token binding failed",
			logger.WithServiceName("api"),
			logger.WithField("action", "refresh_token"),
			zap.Error(err))
		resp := &user.RefreshTokenResp{
			Base: &common.Base{Code: consts.UserReqValidError, Msg: consts.GetErrorCodeMsg(consts.UserReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	code, reToken, acToken, err := Rpc.RefreshTokenRpc(ctx, &user2.RefreshTokenReq{RefreshToken: req.RefreshToken})
	if err != nil {
		logger.Error("refresh token failed",
			logger.WithServiceName("api"),
			logger.WithField("action", "refresh_token"),
			zap.Error(err))
	}
	if code == 0 {
		logger.Info("refresh token success",
			logger.WithServiceName("api"),
			logger.WithField("action", "refresh_token"))
	}
	resp := &user.RefreshTokenResp{
		Base:         &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		RefreshToken: reToken,
		AccessToken:  acToken,
	}
	c.JSON(200, resp)
}
