// Code generated by hertz generator.

package user

import (
	"Tiktok/biz/middleware"
	"Tiktok/biz/model/common"
	"Tiktok/pkg/config"
	"Tiktok/pkg/utils"
	"context"
	"log"
	"path/filepath"

	"Tiktok/biz/model/user"
	Rpc "Tiktok/biz/rpc"
	user2 "Tiktok/kitex_gen/user"
	"Tiktok/pkg/consts"

	"github.com/cloudwego/hertz/pkg/app"
)

// UserRegister .
// @router /user/register [POST]
func UserRegister(ctx context.Context, c *app.RequestContext) {
	var req user.RegisterReq
	err := c.BindAndValidate(&req)
	if err != nil {
		code := consts.UserReqValidError
		resp := &user.RegisterResp{
			Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		}
		c.JSON(200, resp)
		return
	}
	code, err := Rpc.RegisterRpc(ctx, &user2.RegisterReq{
		UserName: req.UserName,
		Password: req.Password,
	})
	if err != nil {
		log.Println("userService.Register error:", err)
	}
	resp := new(user.RegisterResp)
	resp.Base = &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)}
	c.JSON(200, resp)
}

// UserLogin .
// @router /user/login [POST]
func UserLogin(ctx context.Context, c *app.RequestContext) {
	var req user.LoginReq
	err := c.BindAndValidate(&req)
	if err != nil {
		log.Println("userService.Login bind error:", err)
		resp := &user.LoginResp{
			Base: &common.Base{Code: consts.UserReqValidError, Msg: consts.GetErrorCodeMsg(consts.UserReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	code, userInfo, reToken, acToken, err := Rpc.LoginRpc(ctx, &user2.LoginReq{
		UserName: req.UserName,
		Password: req.Password,
		Code:     req.Code,
	})
	if err != nil {
		log.Println("userService.Login error:", err)
	}
	resp := &user.LoginResp{
		Base:         &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data:         userInfo,
		RefreshToken: reToken,
		AccessToken:  acToken,
	}
	c.JSON(200, resp)
}

// UserInfo .
// @router /user/info [GET]
func UserInfo(ctx context.Context, c *app.RequestContext) {
	var req user.UserInfoReq
	err := c.BindAndValidate(&req)
	if err != nil {
		log.Println("userService.Login bind error:", err)
		resp := &user.UserInfoResp{
			Base: &common.Base{Code: consts.UserReqValidError, Msg: consts.GetErrorCodeMsg(consts.UserReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	code, userInfo, err := Rpc.UserInfoRpc(ctx, &user2.UserInfoReq{UserId: req.UserId})
	if err != nil {
		log.Println("userService.UserInfo error:", err)
	}
	resp := &user.UserInfoResp{
		Base: &common.Base{
			Code: code,
			Msg:  consts.GetErrorCodeMsg(code),
		},
		Data: userInfo,
	}
	c.JSON(200, resp)
}

// UserAvatar .
// @router /user/avatar/upload [PUT]
func UserAvatar(ctx context.Context, c *app.RequestContext) {
	var req user.UserAvatarReq
	err := c.BindAndValidate(&req)
	if err != nil {
		log.Println("userService.UserAvatar bind req error:", err)
		resp := &user.UserAvatarResp{
			Base: &common.Base{Code: consts.UserReqValidError, Msg: consts.GetErrorCodeMsg(consts.UserReqValidError)},
		}
		c.JSON(200, resp)
		return
	}

	data, err := c.FormFile("data")
	if err != nil {
		log.Println("userService.UserAvatar FormFile error:", err)
		resp := &user.UserAvatarResp{
			Base: &common.Base{Code: consts.UserReqValidError, Msg: consts.GetErrorCodeMsg(consts.UserReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	file, err := data.Open()
	if err != nil {
		log.Println("userService.UserAvatar data.Open error:", err)
		resp := &user.UserAvatarResp{
			Base: &common.Base{Code: consts.FileError, Msg: consts.GetErrorCodeMsg(consts.FileError)},
			Data: nil,
		}
		c.JSON(200, resp)
	}
	defer func() {
		err = file.Close()
		if err != nil {
			log.Println("file err", err)
		}
	}()
	ok, err := utils.IsImage(file)
	if err != nil {
		log.Println("userService.UserAvatar IsImage error:", err)
		resp := &user.UserAvatarResp{
			Base: &common.Base{Code: consts.FileError, Msg: consts.GetErrorCodeMsg(consts.FileError)},
			Data: nil,
		}
		c.JSON(200, resp)
	}
	if !ok {
		resp := &user.UserAvatarResp{
			Base: &common.Base{Code: consts.ImageFalse, Msg: consts.GetErrorCodeMsg(consts.FileError)},
			Data: nil,
		}
		c.JSON(200, resp)
	}
	filename := utils.IDGenerate()
	code, err := utils.SaveUploadFile(file, config.Cfg.Path.AvatarPath, filename+filepath.Ext(data.Filename))
	if err != nil {
		log.Println(err)
		resp := &user.UserAvatarResp{
			Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(consts.FileError)},
			Data: nil,
		}
		c.JSON(200, resp)
	}

	userId := ctx.Value(middleware.UserIDKey).(string)
	code, userInfo, err := Rpc.UserAvatarRpc(ctx, &user2.UserAvatarReq{
		AvatarURL: "",
		UserID:    userId,
	})
	if err != nil {
		log.Println("userService.UserAvatar error:", err)
	}
	resp := &user.UserAvatarResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data: userInfo,
	}
	c.JSON(200, resp)
}

// RefreshToken .
// @router /user/refresh [POST]
func RefreshToken(ctx context.Context, c *app.RequestContext) {
	var req user.RefreshTokenReq
	err := c.BindAndValidate(&req)
	if err != nil {
		log.Println("userService.RefreshToken bind req error:", err)
		resp := &user.RefreshTokenResp{
			Base: &common.Base{Code: consts.UserReqValidError, Msg: consts.GetErrorCodeMsg(consts.UserReqValidError)},
		}
		c.JSON(200, resp)
		return
	}
	code, reToken, acToken, err := Rpc.RefreshTokenRpc(ctx, &user2.RefreshTokenReq{RefreshToken: req.RefreshToken})
	if err != nil {
		log.Println("userService.RefreshToken error:", err)
	}
	resp := &user.RefreshTokenResp{
		Base:         &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		RefreshToken: reToken,
		AccessToken:  acToken,
	}
	c.JSON(200, resp)
}
