// Code generated by Kitex v0.16.1. DO NOT EDIT.

package react

import (
	"Tiktok/kitex_gen/video"
	"context"

	"github.com/cloudwego/prutal"
)

type CommentInfo struct {
	UserId       string `protobuf:"bytes,1,opt,name=UserId" json:"UserId,omitempty"`
	TargetId     string `protobuf:"bytes,2,opt,name=TargetId" json:"TargetId,omitempty"`
	CommentId    string `protobuf:"bytes,3,opt,name=CommentId" json:"CommentId,omitempty"`
	Content      string `protobuf:"bytes,4,opt,name=Content" json:"Content,omitempty"`
	LikeCount    int64  `protobuf:"varint,5,opt,name=LikeCount" json:"LikeCount,omitempty"`
	CreatedAt    string `protobuf:"bytes,6,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
	UpdatedAt    string `protobuf:"bytes,7,opt,name=UpdatedAt" json:"UpdatedAt,omitempty"`
	DeletedAt    string `protobuf:"bytes,8,opt,name=DeletedAt" json:"DeletedAt,omitempty"`
	TargetType   string `protobuf:"bytes,9,opt,name=TargetType" json:"TargetType,omitempty"`
	CommentCount int64  `protobuf:"varint,10,opt,name=CommentCount" json:"CommentCount,omitempty"`
}

func (x *CommentInfo) Reset() { *x = CommentInfo{} }

func (x *CommentInfo) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CommentInfo) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CommentInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CommentInfo) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *CommentInfo) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *CommentInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentInfo) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *CommentInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CommentInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CommentInfo) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

func (x *CommentInfo) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *CommentInfo) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

type CommentPublishReq struct {
	TargetAt   string `protobuf:"bytes,1,opt,name=TargetAt" json:"TargetAt,omitempty"`
	TargetType string `protobuf:"bytes,2,opt,name=TargetType" json:"TargetType,omitempty"`
	Content    string `protobuf:"bytes,3,opt,name=Content" json:"Content,omitempty"`
	UserID     string `protobuf:"bytes,4,opt,name=UserID" json:"UserID,omitempty"`
}

func (x *CommentPublishReq) Reset() { *x = CommentPublishReq{} }

func (x *CommentPublishReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CommentPublishReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CommentPublishReq) GetTargetAt() string {
	if x != nil {
		return x.TargetAt
	}
	return ""
}

func (x *CommentPublishReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *CommentPublishReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentPublishReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type CommentPublishResp struct {
	Code int32 `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
}

func (x *CommentPublishResp) Reset() { *x = CommentPublishResp{} }

func (x *CommentPublishResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CommentPublishResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CommentPublishResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type CommentListReq struct {
	TargetAt string `protobuf:"bytes,1,opt,name=TargetAt" json:"TargetAt,omitempty"`
	PageSize int64  `protobuf:"varint,2,opt,name=PageSize" json:"PageSize,omitempty"`
	PageNum  int64  `protobuf:"varint,3,opt,name=PageNum" json:"PageNum,omitempty"`
}

func (x *CommentListReq) Reset() { *x = CommentListReq{} }

func (x *CommentListReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CommentListReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CommentListReq) GetTargetAt() string {
	if x != nil {
		return x.TargetAt
	}
	return ""
}

func (x *CommentListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *CommentListReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

type CommentData struct {
	Items []*CommentInfo `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	Total int64          `protobuf:"varint,2,opt,name=Total" json:"Total,omitempty"`
}

func (x *CommentData) Reset() { *x = CommentData{} }

func (x *CommentData) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CommentData) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CommentData) GetItems() []*CommentInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CommentData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CommentListResp struct {
	Code int32        `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Data *CommentData `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
}

func (x *CommentListResp) Reset() { *x = CommentListResp{} }

func (x *CommentListResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CommentListResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CommentListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommentListResp) GetData() *CommentData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CommentDeleteReq struct {
	CommentId  string `protobuf:"bytes,1,opt,name=CommentId" json:"CommentId,omitempty"`
	TargetAt   string `protobuf:"bytes,2,opt,name=TargetAt" json:"TargetAt,omitempty"`
	TargetType string `protobuf:"bytes,3,opt,name=TargetType" json:"TargetType,omitempty"`
	UserID     string `protobuf:"bytes,4,opt,name=UserID" json:"UserID,omitempty"`
}

func (x *CommentDeleteReq) Reset() { *x = CommentDeleteReq{} }

func (x *CommentDeleteReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CommentDeleteReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CommentDeleteReq) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *CommentDeleteReq) GetTargetAt() string {
	if x != nil {
		return x.TargetAt
	}
	return ""
}

func (x *CommentDeleteReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *CommentDeleteReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type CommentDeleteResp struct {
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
}

func (x *CommentDeleteResp) Reset() { *x = CommentDeleteResp{} }

func (x *CommentDeleteResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CommentDeleteResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CommentDeleteResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type LikeActionReq struct {
	TargetAt   string `protobuf:"bytes,1,opt,name=TargetAt" json:"TargetAt,omitempty"`
	TargetType string `protobuf:"bytes,2,opt,name=TargetType" json:"TargetType,omitempty"`
	ActionType string `protobuf:"bytes,3,opt,name=ActionType" json:"ActionType,omitempty"`
	UserID     string `protobuf:"bytes,4,opt,name=UserID" json:"UserID,omitempty"`
}

func (x *LikeActionReq) Reset() { *x = LikeActionReq{} }

func (x *LikeActionReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LikeActionReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LikeActionReq) GetTargetAt() string {
	if x != nil {
		return x.TargetAt
	}
	return ""
}

func (x *LikeActionReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *LikeActionReq) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *LikeActionReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type LikeActionResp struct {
	Code int32 `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
}

func (x *LikeActionResp) Reset() { *x = LikeActionResp{} }

func (x *LikeActionResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LikeActionResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LikeActionResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type LikeListReq struct {
	UserId   string `protobuf:"bytes,1,opt,name=UserId" json:"UserId,omitempty"`
	PageNum  int64  `protobuf:"varint,2,opt,name=PageNum" json:"PageNum,omitempty"`
	PageSize int64  `protobuf:"varint,3,opt,name=PageSize" json:"PageSize,omitempty"`
}

func (x *LikeListReq) Reset() { *x = LikeListReq{} }

func (x *LikeListReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LikeListReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LikeListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LikeListReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *LikeListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type LikeVideoData struct {
	Items []*video.VideoInfo `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	Total int64              `protobuf:"varint,2,opt,name=Total" json:"Total,omitempty"`
}

func (x *LikeVideoData) Reset() { *x = LikeVideoData{} }

func (x *LikeVideoData) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LikeVideoData) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LikeVideoData) GetItems() []*video.VideoInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *LikeVideoData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type LikeListResp struct {
	Code int32          `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Data *LikeVideoData `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
}

func (x *LikeListResp) Reset() { *x = LikeListResp{} }

func (x *LikeListResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LikeListResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LikeListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LikeListResp) GetData() *LikeVideoData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CommentService interface {
	CommentPublish(ctx context.Context, req *CommentPublishReq) (res *CommentPublishResp, err error)
	CommentList(ctx context.Context, req *CommentListReq) (res *CommentListResp, err error)
	CommentDelete(ctx context.Context, req *CommentDeleteReq) (res *CommentDeleteResp, err error)
}

type LikeService interface {
	LikeAction(ctx context.Context, req *LikeActionReq) (res *LikeActionResp, err error)
	LikeList(ctx context.Context, req *LikeListReq) (res *LikeListResp, err error)
}
