// Code generated by Kitex v0.16.1. DO NOT EDIT.

package socialservice

import (
	social "Tiktok/kitex_gen/social"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	RelationAction(ctx context.Context, Req *social.RelationActionReq, callOptions ...callopt.Option) (r *social.RelationActionResp, err error)
	FollowingList(ctx context.Context, Req *social.FollowingListReq, callOptions ...callopt.Option) (r *social.FollowingListResp, err error)
	FollowerList(ctx context.Context, Req *social.FollowerListReq, callOptions ...callopt.Option) (r *social.FollowerListResp, err error)
	FriendList(ctx context.Context, Req *social.FriendListReq, callOptions ...callopt.Option) (r *social.FriendListResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kSocialServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSocialServiceClient struct {
	*kClient
}

func (p *kSocialServiceClient) RelationAction(ctx context.Context, Req *social.RelationActionReq, callOptions ...callopt.Option) (r *social.RelationActionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RelationAction(ctx, Req)
}

func (p *kSocialServiceClient) FollowingList(ctx context.Context, Req *social.FollowingListReq, callOptions ...callopt.Option) (r *social.FollowingListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowingList(ctx, Req)
}

func (p *kSocialServiceClient) FollowerList(ctx context.Context, Req *social.FollowerListReq, callOptions ...callopt.Option) (r *social.FollowerListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowerList(ctx, Req)
}

func (p *kSocialServiceClient) FriendList(ctx context.Context, Req *social.FriendListReq, callOptions ...callopt.Option) (r *social.FriendListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FriendList(ctx, Req)
}
