// Code generated by Kitex v0.16.1. DO NOT EDIT.

package socialservice

import (
	social "Tiktok/kitex_gen/social"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"RelationAction": kitex.NewMethodInfo(
		relationActionHandler,
		newRelationActionArgs,
		newRelationActionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"FollowingList": kitex.NewMethodInfo(
		followingListHandler,
		newFollowingListArgs,
		newFollowingListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"FollowerList": kitex.NewMethodInfo(
		followerListHandler,
		newFollowerListArgs,
		newFollowerListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"FriendList": kitex.NewMethodInfo(
		friendListHandler,
		newFriendListArgs,
		newFriendListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	socialServiceServiceInfo                = NewServiceInfo()
	socialServiceServiceInfoForClient       = NewServiceInfoForClient()
	socialServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return socialServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return socialServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return socialServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "SocialService"
	handlerType := (*social.SocialService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "social",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func relationActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(social.RelationActionReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(social.SocialService).RelationAction(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RelationActionArgs:
		success, err := handler.(social.SocialService).RelationAction(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RelationActionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRelationActionArgs() interface{} {
	return &RelationActionArgs{}
}

func newRelationActionResult() interface{} {
	return &RelationActionResult{}
}

type RelationActionArgs struct {
	Req *social.RelationActionReq
}

func (p *RelationActionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RelationActionArgs) Unmarshal(in []byte) error {
	msg := new(social.RelationActionReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RelationActionArgs_Req_DEFAULT *social.RelationActionReq

func (p *RelationActionArgs) GetReq() *social.RelationActionReq {
	if !p.IsSetReq() {
		return RelationActionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RelationActionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RelationActionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RelationActionResult struct {
	Success *social.RelationActionResp
}

var RelationActionResult_Success_DEFAULT *social.RelationActionResp

func (p *RelationActionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RelationActionResult) Unmarshal(in []byte) error {
	msg := new(social.RelationActionResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RelationActionResult) GetSuccess() *social.RelationActionResp {
	if !p.IsSetSuccess() {
		return RelationActionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RelationActionResult) SetSuccess(x interface{}) {
	p.Success = x.(*social.RelationActionResp)
}

func (p *RelationActionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RelationActionResult) GetResult() interface{} {
	return p.Success
}

func followingListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(social.FollowingListReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(social.SocialService).FollowingList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *FollowingListArgs:
		success, err := handler.(social.SocialService).FollowingList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FollowingListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newFollowingListArgs() interface{} {
	return &FollowingListArgs{}
}

func newFollowingListResult() interface{} {
	return &FollowingListResult{}
}

type FollowingListArgs struct {
	Req *social.FollowingListReq
}

func (p *FollowingListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *FollowingListArgs) Unmarshal(in []byte) error {
	msg := new(social.FollowingListReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FollowingListArgs_Req_DEFAULT *social.FollowingListReq

func (p *FollowingListArgs) GetReq() *social.FollowingListReq {
	if !p.IsSetReq() {
		return FollowingListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FollowingListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FollowingListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type FollowingListResult struct {
	Success *social.FollowingListResp
}

var FollowingListResult_Success_DEFAULT *social.FollowingListResp

func (p *FollowingListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *FollowingListResult) Unmarshal(in []byte) error {
	msg := new(social.FollowingListResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FollowingListResult) GetSuccess() *social.FollowingListResp {
	if !p.IsSetSuccess() {
		return FollowingListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FollowingListResult) SetSuccess(x interface{}) {
	p.Success = x.(*social.FollowingListResp)
}

func (p *FollowingListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FollowingListResult) GetResult() interface{} {
	return p.Success
}

func followerListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(social.FollowerListReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(social.SocialService).FollowerList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *FollowerListArgs:
		success, err := handler.(social.SocialService).FollowerList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FollowerListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newFollowerListArgs() interface{} {
	return &FollowerListArgs{}
}

func newFollowerListResult() interface{} {
	return &FollowerListResult{}
}

type FollowerListArgs struct {
	Req *social.FollowerListReq
}

func (p *FollowerListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *FollowerListArgs) Unmarshal(in []byte) error {
	msg := new(social.FollowerListReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FollowerListArgs_Req_DEFAULT *social.FollowerListReq

func (p *FollowerListArgs) GetReq() *social.FollowerListReq {
	if !p.IsSetReq() {
		return FollowerListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FollowerListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FollowerListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type FollowerListResult struct {
	Success *social.FollowerListResp
}

var FollowerListResult_Success_DEFAULT *social.FollowerListResp

func (p *FollowerListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *FollowerListResult) Unmarshal(in []byte) error {
	msg := new(social.FollowerListResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FollowerListResult) GetSuccess() *social.FollowerListResp {
	if !p.IsSetSuccess() {
		return FollowerListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FollowerListResult) SetSuccess(x interface{}) {
	p.Success = x.(*social.FollowerListResp)
}

func (p *FollowerListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FollowerListResult) GetResult() interface{} {
	return p.Success
}

func friendListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(social.FriendListReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(social.SocialService).FriendList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *FriendListArgs:
		success, err := handler.(social.SocialService).FriendList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FriendListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newFriendListArgs() interface{} {
	return &FriendListArgs{}
}

func newFriendListResult() interface{} {
	return &FriendListResult{}
}

type FriendListArgs struct {
	Req *social.FriendListReq
}

func (p *FriendListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *FriendListArgs) Unmarshal(in []byte) error {
	msg := new(social.FriendListReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FriendListArgs_Req_DEFAULT *social.FriendListReq

func (p *FriendListArgs) GetReq() *social.FriendListReq {
	if !p.IsSetReq() {
		return FriendListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FriendListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FriendListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type FriendListResult struct {
	Success *social.FriendListResp
}

var FriendListResult_Success_DEFAULT *social.FriendListResp

func (p *FriendListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *FriendListResult) Unmarshal(in []byte) error {
	msg := new(social.FriendListResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FriendListResult) GetSuccess() *social.FriendListResp {
	if !p.IsSetSuccess() {
		return FriendListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FriendListResult) SetSuccess(x interface{}) {
	p.Success = x.(*social.FriendListResp)
}

func (p *FriendListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FriendListResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) RelationAction(ctx context.Context, Req *social.RelationActionReq) (r *social.RelationActionResp, err error) {
	var _args RelationActionArgs
	_args.Req = Req
	var _result RelationActionResult
	if err = p.c.Call(ctx, "RelationAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FollowingList(ctx context.Context, Req *social.FollowingListReq) (r *social.FollowingListResp, err error) {
	var _args FollowingListArgs
	_args.Req = Req
	var _result FollowingListResult
	if err = p.c.Call(ctx, "FollowingList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FollowerList(ctx context.Context, Req *social.FollowerListReq) (r *social.FollowerListResp, err error) {
	var _args FollowerListArgs
	_args.Req = Req
	var _result FollowerListResult
	if err = p.c.Call(ctx, "FollowerList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FriendList(ctx context.Context, Req *social.FriendListReq) (r *social.FriendListResp, err error) {
	var _args FriendListArgs
	_args.Req = Req
	var _result FriendListResult
	if err = p.c.Call(ctx, "FriendList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
