syntax="proto3";
package mfa;
option go_package="mfa";

message MfaData{
    string Secret=1;
    string Qrcode=2;
}

message MfaQrcodeReq{
    string UserName=1;
    string UserID=2;
}
message MfaQrcodeResp{
    int32 Code=1;
    MfaData Data=2;
}

message MfaBindReq{
    string mfaCode=1;
    string Secret=2;
    string UserID=3;
    string Type=4;
}
message MfaBindResp{
    int32 Code=1;
}
service MfaService{
    rpc MfaQrcode(MfaQrcodeReq) returns(MfaQrcodeResp){}
    rpc MfaBind(MfaBindReq)returns(MfaBindResp){}
}
