mysql:
  host: "localhost"
#  host: "172.17.0.1"
  port: 3306
  user: "root"
  database: "tiktok"
  charset: "utf8"
  parse_time: true
  loc: "Local"
redis:
  host: "localhost"
#  host: "172.17.0.1"
  port: "6379"
  password: "root"
  db: 0
api:
  base_url: "https://api.minimaxi.com"
  map_api: "55d0d6f2c5dac90846566a854debba5c"
filepath:
  video_path: "/home/lai-long/Tiktok/a/"
  avatar_path: "/home/lai-long/Tiktok/a/"
  env_path: "/home/lai-long/Tiktok/.env"
mcp:
  clients:
  - id: "mcp_client_1"
    name: "mcp"
    connection_type: "stdio"
    command: "/home/lai-long/Tiktok/mcp_service/mcp_service"
    args: []
    tools_to_execute: ["*"]
    tools_to_auto_execute: ["*"]
  tool_manager:
    tool_execution_timeout: 200
    max_agent_depth: 10
