mysql:
  host: "localhost"
#  host: "172.17.0.1"
  port: 3306
  user: "root"
  database: "tiktok"
  charset: "utf8"
  parse_time: true
  loc: "Local"
redis:
  host: "localhost"
#  host: "172.17.0.1"
  port: "6379"
  password: "root"
  db: 0
api:
  base_url: "https://api.minimaxi.com"
filepath:
  video_path: "/home/lai-long/Tiktok/a/"
  avatar_path: "/home/lai-long/Tiktok/a/"
  env_path: "/home/lai-long/Tiktok/.env"
