flow:
  - resource: "UserRegister"
    threshold: 50
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0

  - resource: "UserLogin"
    threshold: 100
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0

  - resource: "UserInfo"
    threshold: 200
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0

  - resource: "UserAvatar"
    threshold: 20
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0

  - resource: "RefreshToken"
    threshold: 100
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0

  - resource: "VideoPublish"
    threshold: 10
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0

  - resource: "VideoList"
    threshold: 300
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0

  - resource: "VideoSearch"
    threshold: 100
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0

  - resource: "VideoPopular"
    threshold: 200
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0

  - resource: "RelationAction"
    threshold: 50
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0

  - resource: "FollowingList"
    threshold: 200
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0

  - resource: "FollowerList"
    threshold: 200
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0

  - resource: "FriendList"
    threshold: 200
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0

  - resource: "LikeAction"
    threshold: 100
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0

  - resource: "LikeList"
    threshold: 200
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0

  - resource: "CommentPublish"
    threshold: 50
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0

  - resource: "CommentList"
    threshold: 200
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0

  - resource: "CommentDelete"
    threshold: 50
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0

  - resource: "MfaQrcode"
    threshold: 20
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0

  - resource: "MfaBind"
    threshold: 20
    controlBehavior: 0
    maxQueueingTimeMs: 0
    warmUpPeriodSec: 0


circuitBreaker:

  - resource: "UserRegister"
    threshold: 0.3
    strategy: errorRatio
    retryTimeoutMs: 5000
    minRequestAmount: 10
    maxAllowedRtMs: 0

  - resource: "UserLogin"
    threshold: 0.5
    strategy: slowRequestRatio
    retryTimeoutMs: 3000
    minRequestAmount: 5
    maxAllowedRtMs: 1000

  - resource: "UserInfo"
    threshold: 0.5
    strategy: slowRequestRatio
    retryTimeoutMs: 3000
    minRequestAmount: 5
    maxAllowedRtMs: 1000

  - resource: "UserAvatar"
    threshold: 0.5
    strategy: slowRequestRatio
    retryTimeoutMs: 5000
    minRequestAmount: 3
    maxAllowedRtMs: 3000

  - resource: "RefreshToken"
    threshold: 0.5
    strategy: slowRequestRatio
    retryTimeoutMs: 3000
    minRequestAmount: 5
    maxAllowedRtMs: 500

  - resource: "VideoPublish"
    threshold: 0.5
    strategy: slowRequestRatio
    retryTimeoutMs: 5000
    minRequestAmount: 3
    maxAllowedRtMs: 5000

  - resource: "VideoList"
    threshold: 0.5
    strategy: slowRequestRatio
    retryTimeoutMs: 3000
    minRequestAmount: 5
    maxAllowedRtMs: 1000

  - resource: "VideoSearch"
    threshold: 0.5
    strategy: slowRequestRatio
    retryTimeoutMs: 3000
    minRequestAmount: 5
    maxAllowedRtMs: 2000

  - resource: "VideoPopular"
    threshold: 0.5
    strategy: slowRequestRatio
    retryTimeoutMs: 3000
    minRequestAmount: 5
    maxAllowedRtMs: 2000

  - resource: "RelationAction"
    threshold: 0.3
    strategy: errorRatio
    retryTimeoutMs: 5000
    minRequestAmount: 5
    maxAllowedRtMs: 0

  - resource: "FollowingList"
    threshold: 0.5
    strategy: slowRequestRatio
    retryTimeoutMs: 3000
    minRequestAmount: 5
    maxAllowedRtMs: 1000

  - resource: "FollowerList"
    threshold: 0.5
    strategy: slowRequestRatio
    retryTimeoutMs: 3000
    minRequestAmount: 5
    maxAllowedRtMs: 1000

  - resource: "FriendList"
    threshold: 0.5
    strategy: slowRequestRatio
    retryTimeoutMs: 3000
    minRequestAmount: 5
    maxAllowedRtMs: 1000

  - resource: "LikeAction"
    threshold: 0.3
    strategy: errorRatio
    retryTimeoutMs: 3000
    minRequestAmount: 5
    maxAllowedRtMs: 0

  - resource: "LikeList"
    threshold: 0.5
    strategy: slowRequestRatio
    retryTimeoutMs: 3000
    minRequestAmount: 5
    maxAllowedRtMs: 1000

  - resource: "CommentPublish"
    threshold: 0.3
    strategy: errorRatio
    retryTimeoutMs: 3000
    minRequestAmount: 5
    maxAllowedRtMs: 0

  - resource: "CommentList"
    threshold: 0.5
    strategy: slowRequestRatio
    retryTimeoutMs: 3000
    minRequestAmount: 5
    maxAllowedRtMs: 1000

  - resource: "CommentDelete"
    threshold: 0.3
    strategy: errorRatio
    retryTimeoutMs: 3000
    minRequestAmount: 5
    maxAllowedRtMs: 0

  - resource: "MfaQrcode"
    threshold: 0.5
    strategy: slowRequestRatio
    retryTimeoutMs: 3000
    minRequestAmount: 5
    maxAllowedRtMs: 1000

  - resource: "MfaBind"
    threshold: 0.3
    strategy: errorRatio
    retryTimeoutMs: 3000
    minRequestAmount: 5
    maxAllowedRtMs: 0
