// Code generated by Kitex v0.16.1. DO NOT EDIT.

package social

import (
	"context"

	"github.com/cloudwego/prutal"
)

type UserInfo struct {
	ID        string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=Username" json:"Username,omitempty"`
	AvatarURL string `protobuf:"bytes,3,opt,name=AvatarURL" json:"AvatarURL,omitempty"`
	CreatedAt string `protobuf:"bytes,4,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
	UpdatedAt string `protobuf:"bytes,5,opt,name=UpdatedAt" json:"UpdatedAt,omitempty"`
	DeletedAt string `protobuf:"bytes,6,opt,name=DeletedAt" json:"DeletedAt,omitempty"`
}

func (x *UserInfo) Reset() { *x = UserInfo{} }

func (x *UserInfo) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserInfo) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserInfo) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetAvatarURL() string {
	if x != nil {
		return x.AvatarURL
	}
	return ""
}

func (x *UserInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UserInfo) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type SocialData struct {
	Items []*UserInfo `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	Total int64       `protobuf:"varint,2,opt,name=Total" json:"Total,omitempty"`
}

func (x *SocialData) Reset() { *x = SocialData{} }

func (x *SocialData) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SocialData) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SocialData) GetItems() []*UserInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SocialData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RelationActionReq struct {
	ToUserId   string `protobuf:"bytes,1,opt,name=ToUserId" json:"ToUserId,omitempty"`
	ActionType string `protobuf:"bytes,2,opt,name=ActionType" json:"ActionType,omitempty"`
	UserId     string `protobuf:"bytes,3,opt,name=UserId" json:"UserId,omitempty"`
}

func (x *RelationActionReq) Reset() { *x = RelationActionReq{} }

func (x *RelationActionReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RelationActionReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RelationActionReq) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *RelationActionReq) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *RelationActionReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RelationActionResp struct {
	Code int32  `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg" json:"Msg,omitempty"`
}

func (x *RelationActionResp) Reset() { *x = RelationActionResp{} }

func (x *RelationActionResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RelationActionResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RelationActionResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RelationActionResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type FollowingListReq struct {
	UserId   string `protobuf:"bytes,1,opt,name=UserId" json:"UserId,omitempty"`
	PageNum  int64  `protobuf:"varint,2,opt,name=PageNum" json:"PageNum,omitempty"`
	PageSize int64  `protobuf:"varint,3,opt,name=PageSize" json:"PageSize,omitempty"`
}

func (x *FollowingListReq) Reset() { *x = FollowingListReq{} }

func (x *FollowingListReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FollowingListReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FollowingListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FollowingListReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *FollowingListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type FollowingListResp struct {
	Code int32       `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	Msg  string      `protobuf:"bytes,2,opt,name=Msg" json:"Msg,omitempty"`
	Data *SocialData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (x *FollowingListResp) Reset() { *x = FollowingListResp{} }

func (x *FollowingListResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FollowingListResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FollowingListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FollowingListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FollowingListResp) GetData() *SocialData {
	if x != nil {
		return x.Data
	}
	return nil
}

type FollowerListReq struct {
	UserId   string `protobuf:"bytes,1,opt,name=UserId" json:"UserId,omitempty"`
	PageNum  int64  `protobuf:"varint,2,opt,name=PageNum" json:"PageNum,omitempty"`
	PageSize int64  `protobuf:"varint,3,opt,name=PageSize" json:"PageSize,omitempty"`
}

func (x *FollowerListReq) Reset() { *x = FollowerListReq{} }

func (x *FollowerListReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FollowerListReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FollowerListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FollowerListReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *FollowerListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type FollowerListResp struct {
	Code int32       `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	Msg  string      `protobuf:"bytes,2,opt,name=Msg" json:"Msg,omitempty"`
	Data *SocialData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (x *FollowerListResp) Reset() { *x = FollowerListResp{} }

func (x *FollowerListResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FollowerListResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FollowerListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FollowerListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FollowerListResp) GetData() *SocialData {
	if x != nil {
		return x.Data
	}
	return nil
}

type FriendListReq struct {
	UserId   string `protobuf:"bytes,1,opt,name=UserId" json:"UserId,omitempty"`
	PageNum  int64  `protobuf:"varint,2,opt,name=PageNum" json:"PageNum,omitempty"`
	PageSize int64  `protobuf:"varint,3,opt,name=PageSize" json:"PageSize,omitempty"`
}

func (x *FriendListReq) Reset() { *x = FriendListReq{} }

func (x *FriendListReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FriendListReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FriendListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FriendListReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *FriendListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type FriendListResp struct {
	Code int32       `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	Msg  string      `protobuf:"bytes,2,opt,name=Msg" json:"Msg,omitempty"`
	Data *SocialData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (x *FriendListResp) Reset() { *x = FriendListResp{} }

func (x *FriendListResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FriendListResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FriendListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FriendListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FriendListResp) GetData() *SocialData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SocialService interface {
	RelationAction(ctx context.Context, req *RelationActionReq) (res *RelationActionResp, err error)
	FollowingList(ctx context.Context, req *FollowingListReq) (res *FollowingListResp, err error)
	FollowerList(ctx context.Context, req *FollowerListReq) (res *FollowerListResp, err error)
	FriendList(ctx context.Context, req *FriendListReq) (res *FriendListResp, err error)
}
