// Code generated by hertz generator.

package mfa

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mfaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mfabindMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mfaqrcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}
