// Code generated by hertz generator.

package mfa

import (
	"Tiktok/biz/middleware"
	"Tiktok/biz/model/common"
	"context"
	"log"

	mfa "Tiktok/biz/model/mfa"

	"Tiktok/pkg/consts"

	"github.com/cloudwego/hertz/pkg/app"
)

var (
	MfaQrcode func(ctx context.Context, c *app.RequestContext)
	MfaBind   func(ctx context.Context, c *app.RequestContext)
)

type MfaServer interface {
	GenerateMfa(username string, userId string) (string, string, int32, error)
	MfaBindByCode(code string, userId string) (int32, error)
	MfaBindBySecret(secret string, userId string) (int32, error)
}
type MfaHandler struct {
	MfaService MfaServer
}

func NewMfaHandler(mfaService MfaServer) *MfaHandler {
	return &MfaHandler{
		MfaService: mfaService,
	}
}

// MfaQrcode .
// @router /auth/mfa/qrcode [GET]
func (h *MfaHandler) MfaQrcode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mfa.MfaQrcodeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := &mfa.MfaQrcodeResp{
			Base: &common.Base{Code: consts.UserReqValidError},
		}
		c.JSON(200, resp)
		return
	}
	userId := ctx.Value(middleware.UserIDKey).(string)
	userName := ctx.Value(middleware.UsernameKey).(string)
	key, secret, code, err := h.MfaService.GenerateMfa(userName, userId)
	if err != nil {
		log.Println("MfaQrcode err: ", err)
	}
	resp := &mfa.MfaQrcodeResp{
		Base: &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)},
		Data: &mfa.MfaData{Secret: secret, Qrcode: key},
	}
	c.JSON(200, resp)
}

// MfaBind .
// @router /auth/mfa/bind [POST]
func (h *MfaHandler) MfaBind(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mfa.MfaBindReq
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := &mfa.MfaQrcodeResp{
			Base: &common.Base{Code: consts.UserReqValidError},
		}
		c.JSON(200, resp)
		return
	}
	resp := new(mfa.MfaBindResp)
	var code int32
	userId := ctx.Value(middleware.UserIDKey).(string)
	if req.Secret != "" {
		code, err = h.MfaService.MfaBindBySecret(req.Secret, userId)
	} else {
		code, err = h.MfaService.MfaBindByCode(req.Code, userId)
	}
	if err != nil {
		log.Println("MfaBind err: ", err)
	}
	resp.Base = &common.Base{Code: code, Msg: consts.GetErrorCodeMsg(code)}
	c.JSON(200, resp)
}
