// Code generated by hertz generator.

package mfa

import (
	"Tiktok/biz/model/common"
	"context"

	mfa "Tiktok/biz/model/mfa"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

var (
	MfaQrcode func(ctx context.Context, c *app.RequestContext)
	MfaBind   func(ctx context.Context, c *app.RequestContext)
)

type MfaServer interface {
	GenerateMfa(username string, userId string) (bool, string, string, int, string)
	MfaBindByCode(code string, userId string) (int, string)
	MfaBindBySecret(secret string, userId string) (int, string)
}
type MfaHandler struct {
	MfaService MfaServer
}

func NewMfaHandler(mfaService MfaServer) *MfaHandler {
	return &MfaHandler{
		MfaService: mfaService,
	}
}

// MfaQrcode .
// @router /auth/mfa/qrcode [GET]
func (h *MfaHandler) MfaQrcode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mfa.MfaQrcodeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	userId, _ := ctx.Value("user_id").(string)
	userName, _ := ctx.Value("username").(string)
	_, key, secret, code, msg := h.MfaService.GenerateMfa(userName, userId)
	resp := &mfa.MfaQrcodeResp{
		Base: &common.Base{Code: int32(code), Msg: msg},

		Data: &mfa.MfaData{Secret: secret, Qrcode: key},
	}
	c.JSON(consts.StatusOK, resp)
}

// MfaBind .
// @router /auth/mfa/bind [POST]
func (h *MfaHandler) MfaBind(ctx context.Context, c *app.RequestContext) {
	var err error
	var req mfa.MfaBindReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := new(mfa.MfaBindResp)
	var code int
	var msg string
	userId, _ := ctx.Value("user_id").(string)
	if req.Secret != "" {
		code, msg = h.MfaService.MfaBindBySecret(req.Secret, req.Secret)
	} else {
		code, msg = h.MfaService.MfaBindByCode(req.Code, userId)
	}
	resp.Base.Msg = msg
	resp.Base.Code = int32(code)
	c.JSON(consts.StatusOK, resp)
}
