// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	chat "Tiktok/biz/router/chat"
	mfa "Tiktok/biz/router/mfa"
	react "Tiktok/biz/router/react"
	social "Tiktok/biz/router/social"
	user "Tiktok/biz/router/user"
	video "Tiktok/biz/router/video"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	chat.Register(r)
	video.Register(r)
	social.Register(r)
	react.Register(r)
	mfa.Register(r)
	user.Register(r)
}
