// Code generated by Kitex v0.16.1. DO NOT EDIT.

package user

import (
	"context"

	"github.com/cloudwego/prutal"
)

type UserInfo struct {
	ID        string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=Username" json:"Username,omitempty"`
	AvatarURL string `protobuf:"bytes,3,opt,name=AvatarURL" json:"AvatarURL,omitempty"`
	CreatedAt string `protobuf:"bytes,4,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
	UpdatedAt string `protobuf:"bytes,5,opt,name=UpdatedAt" json:"UpdatedAt,omitempty"`
	DeletedAt string `protobuf:"bytes,6,opt,name=DeletedAt" json:"DeletedAt,omitempty"`
}

func (x *UserInfo) Reset() { *x = UserInfo{} }

func (x *UserInfo) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserInfo) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserInfo) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetAvatarURL() string {
	if x != nil {
		return x.AvatarURL
	}
	return ""
}

func (x *UserInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UserInfo) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type RegisterReq struct {
	UserName string `protobuf:"bytes,1,opt,name=UserName" json:"UserName,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
}

func (x *RegisterReq) Reset() { *x = RegisterReq{} }

func (x *RegisterReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RegisterReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RegisterReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResp struct {
	Code int32 `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
}

func (x *RegisterResp) Reset() { *x = RegisterResp{} }

func (x *RegisterResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RegisterResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RegisterResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type LoginReq struct {
	UserName string `protobuf:"bytes,1,opt,name=UserName" json:"UserName,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
	Code     string `protobuf:"bytes,3,opt,name=Code" json:"Code,omitempty"`
}

func (x *LoginReq) Reset() { *x = LoginReq{} }

func (x *LoginReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LoginReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoginReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type LoginResp struct {
	Code         int32     `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	Data         *UserInfo `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	RefreshToken string    `protobuf:"bytes,3,opt,name=RefreshToken" json:"RefreshToken,omitempty"`
	AccessToken  string    `protobuf:"bytes,4,opt,name=AccessToken" json:"AccessToken,omitempty"`
}

func (x *LoginResp) Reset() { *x = LoginResp{} }

func (x *LoginResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LoginResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoginResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginResp) GetData() *UserInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LoginResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type UserInfoReq struct {
	UserId string `protobuf:"bytes,1,opt,name=UserId" json:"UserId,omitempty"`
}

func (x *UserInfoReq) Reset() { *x = UserInfoReq{} }

func (x *UserInfoReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserInfoReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserInfoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserInfoResp struct {
	Code int32     `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	Data *UserInfo `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
}

func (x *UserInfoResp) Reset() { *x = UserInfoResp{} }

func (x *UserInfoResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserInfoResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserInfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserInfoResp) GetData() *UserInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserAvatarReq struct {
	AvatarURL string `protobuf:"bytes,1,opt,name=AvatarURL" json:"AvatarURL,omitempty"`
	UserID    string `protobuf:"bytes,2,opt,name=UserID" json:"UserID,omitempty"`
}

func (x *UserAvatarReq) Reset() { *x = UserAvatarReq{} }

func (x *UserAvatarReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserAvatarReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserAvatarReq) GetAvatarURL() string {
	if x != nil {
		return x.AvatarURL
	}
	return ""
}

func (x *UserAvatarReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type UserAvatarResp struct {
	Code int32     `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	Data *UserInfo `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (x *UserAvatarResp) Reset() { *x = UserAvatarResp{} }

func (x *UserAvatarResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserAvatarResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserAvatarResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserAvatarResp) GetData() *UserInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type RefreshTokenReq struct {
	RefreshToken string `protobuf:"bytes,1,opt,name=RefreshToken" json:"RefreshToken,omitempty"`
}

func (x *RefreshTokenReq) Reset() { *x = RefreshTokenReq{} }

func (x *RefreshTokenReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RefreshTokenReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RefreshTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResp struct {
	Code         int32  `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	RefreshToken string `protobuf:"bytes,2,opt,name=RefreshToken" json:"RefreshToken,omitempty"`
	AccessToken  string `protobuf:"bytes,3,opt,name=AccessToken" json:"AccessToken,omitempty"`
}

func (x *RefreshTokenResp) Reset() { *x = RefreshTokenResp{} }

func (x *RefreshTokenResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RefreshTokenResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RefreshTokenResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RefreshTokenResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type AuthReq struct {
	AccessToken string `protobuf:"bytes,1,opt,name=AccessToken" json:"AccessToken,omitempty"`
}

func (x *AuthReq) Reset() { *x = AuthReq{} }

func (x *AuthReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *AuthReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AuthReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type AuthResp struct {
	Code int32 `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
}

func (x *AuthResp) Reset() { *x = AuthResp{} }

func (x *AuthResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *AuthResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AuthResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type MfaData struct {
	Secret string `protobuf:"bytes,1,opt,name=Secret" json:"Secret,omitempty"`
	Qrcode string `protobuf:"bytes,2,opt,name=Qrcode" json:"Qrcode,omitempty"`
}

func (x *MfaData) Reset() { *x = MfaData{} }

func (x *MfaData) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MfaData) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MfaData) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *MfaData) GetQrcode() string {
	if x != nil {
		return x.Qrcode
	}
	return ""
}

type MfaQrcodeReq struct {
	UserName string `protobuf:"bytes,1,opt,name=UserName" json:"UserName,omitempty"`
	UserID   string `protobuf:"bytes,2,opt,name=UserID" json:"UserID,omitempty"`
}

func (x *MfaQrcodeReq) Reset() { *x = MfaQrcodeReq{} }

func (x *MfaQrcodeReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MfaQrcodeReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MfaQrcodeReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *MfaQrcodeReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type MfaQrcodeResp struct {
	Code int32    `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	Data *MfaData `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
}

func (x *MfaQrcodeResp) Reset() { *x = MfaQrcodeResp{} }

func (x *MfaQrcodeResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MfaQrcodeResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MfaQrcodeResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MfaQrcodeResp) GetData() *MfaData {
	if x != nil {
		return x.Data
	}
	return nil
}

type MfaBindReq struct {
	MfaCode string `protobuf:"bytes,1,opt,name=mfaCode" json:"mfaCode,omitempty"`
	Secret  string `protobuf:"bytes,2,opt,name=Secret" json:"Secret,omitempty"`
	UserID  string `protobuf:"bytes,3,opt,name=UserID" json:"UserID,omitempty"`
	Type    string `protobuf:"bytes,4,opt,name=Type" json:"Type,omitempty"`
}

func (x *MfaBindReq) Reset() { *x = MfaBindReq{} }

func (x *MfaBindReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MfaBindReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MfaBindReq) GetMfaCode() string {
	if x != nil {
		return x.MfaCode
	}
	return ""
}

func (x *MfaBindReq) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *MfaBindReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *MfaBindReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type MfaBindResp struct {
	Code int32 `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
}

func (x *MfaBindResp) Reset() { *x = MfaBindResp{} }

func (x *MfaBindResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MfaBindResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MfaBindResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type MfaConfirmReq struct {
	UserID string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	QrCode string `protobuf:"bytes,2,opt,name=QrCode" json:"QrCode,omitempty"`
}

func (x *MfaConfirmReq) Reset() { *x = MfaConfirmReq{} }

func (x *MfaConfirmReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MfaConfirmReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MfaConfirmReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *MfaConfirmReq) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

type MfaConfirmResp struct {
	Code int32 `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
}

func (x *MfaConfirmResp) Reset() { *x = MfaConfirmResp{} }

func (x *MfaConfirmResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MfaConfirmResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MfaConfirmResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type UserService interface {
	UserRegister(ctx context.Context, req *RegisterReq) (res *RegisterResp, err error)
	UserLogin(ctx context.Context, req *LoginReq) (res *LoginResp, err error)
	UserInfo(ctx context.Context, req *UserInfoReq) (res *UserInfoResp, err error)
	UserAvatar(ctx context.Context, req *UserAvatarReq) (res *UserAvatarResp, err error)
	RefreshToken(ctx context.Context, req *RefreshTokenReq) (res *RefreshTokenResp, err error)
	MfaQrcode(ctx context.Context, req *MfaQrcodeReq) (res *MfaQrcodeResp, err error)
	MfaBind(ctx context.Context, req *MfaBindReq) (res *MfaBindResp, err error)
	MfaConfirm(ctx context.Context, req *MfaConfirmReq) (res *MfaConfirmResp, err error)
}
